-- Terceira expansão da biblioteca de exercícios: 249 exercícios novos, que
-- levam a biblioteca semeada a 1000. Só insere; nada do que já existe é
-- alterado. Critérios, grupos e equipamentos iguais aos de
-- 20261102010000_exercise_library_expansao_2.sql (nomes conferidos contra a
-- biblioteca e os planos prontos, inclusive pelo inglês; sem variação só de
-- pausa, cadência ou posição dos pés).
--
-- Entram aqui os levantamentos olímpicos (Power Clean, Hang Clean, Power
-- Snatch, Push Jerk), todos no avançado.
--
-- Com 1000 linhas a biblioteca encosta no limite padrão de linhas por consulta
-- do PostgREST: as buscas que trazem a biblioteca inteira (troca de exercício
-- no app, biblioteca e demonstrações no painel) passam a paginar.
--
-- on conflict (nome) do nothing: reaplicar a migration (ou um admin já ter
-- cadastrado algum destes pelo painel) não duplica nem sobrescreve.
insert into public.exercise_library
  (nome, grupo_muscular, tipo, equipamento, series, reps, descanso, tecnica, is_post_workout, nivel_minimo)
values
-- Peito
('Supino Larsen', 'peito', 'composto', 'barra', '4', '8-10', '90s', 'Pernas estendidas no ar, sem apoio dos pés', false, 'intermediario'),
('Supino com Pino (Pin Press)', 'peito', 'composto', 'barra', '4', '5-6', '2min', 'Barra parte dos pinos do rack a cada repetição', false, 'avancado'),
('Supino com Tábua (Board Press)', 'peito', 'composto', 'barra', '4', '5-6', '2min', 'Tábua no peito encurta a descida, carga alta', false, 'avancado'),
('Supino com Ponte de Glúteo', 'peito', 'composto', 'halteres', '4', '8-10', '90s', 'Quadril elevado no chão, simula o declinado', false, 'iniciante'),
('Press de Peito Landmine', 'peito', 'composto', 'barra', '4', '8-10', '90s', 'Duas mãos na ponta da barra, aperta e empurra', false, 'iniciante'),
('Crucifixo Unilateral na Máquina', 'peito', 'isolado', 'máquina', '3', '12-15', '45s', 'Um braço por vez, tronco não gira', false, 'iniciante'),
('Crucifixo com Deslizamento', 'peito', 'isolado', 'peso corporal', '3', '6-8', '90s', 'Mãos deslizam pros lados, peito quase no chão', false, 'avancado'),
('Pullover com Kettlebell', 'peito', 'isolado', 'kettlebell', '3', '12-15', '45s', 'Segura pelas alças laterais, desce atrás da cabeça', false, 'iniciante'),
('Pullover na Bola Suíça', 'peito', 'isolado', 'bola', '3', '12-15', '45s', 'Ombros na bola, quadril alto, halter atrás da cabeça', false, 'intermediario'),
('Flexão na Parede', 'peito', 'composto', 'peso corporal', '3', '12-15', '45s', 'Mãos na parede, corpo inclinado e reto', false, 'iniciante'),
('Flexão Negativa', 'peito', 'composto', 'peso corporal', '3', '6-8', '60s', 'Desce em 5s e volta ao topo pelos joelhos', false, 'iniciante'),
('Flexão nos Punhos Cerrados', 'peito', 'composto', 'peso corporal', '3', '10-12', '60s', 'Apoio nos nós dos dedos, punho reto', false, 'intermediario'),
('Flexão com Toque no Ombro', 'peito', 'composto', 'peso corporal', '3', '8-10', '75s', 'No topo, uma mão toca o ombro oposto', false, 'intermediario'),
('Flexão Alternada na Medicine Ball', 'peito', 'composto', 'medicine ball', '3', '8-10', '75s', 'Uma mão na bola, troca de lado a cada repetição', false, 'intermediario'),
('Flexão Cruzando o Step', 'peito', 'composto', 'peso corporal', '3', '8-10', '75s', 'Uma mão no step, atravessa pro outro lado', false, 'intermediario'),
('Flexão Pseudo-Prancha', 'peito', 'composto', 'peso corporal', '4', '6-8', '90s', 'Mãos na linha da cintura, ombros à frente', false, 'avancado'),
('Paralelas Negativas', 'peito', 'composto', 'peso corporal', '4', '5-6', '90s', 'Sobe com um salto e desce em 5s', false, 'intermediario'),
('Arremesso de Medicine Ball Deitado', 'peito', 'composto', 'medicine ball', '4', '8-10', '60s', 'Deitado, arremessa pra cima e amortece na volta', false, 'intermediario'),

-- Costas
('Barra Fixa com Pegada Fechada', 'costas', 'composto', 'peso corporal', '4', '8-10', '90s', 'Mãos quase juntas, palmas pra frente', false, 'intermediario'),
('Barra Fixa com Pegada Mista', 'costas', 'composto', 'peso corporal', '4', '8-10', '90s', 'Uma palma pra frente e outra pra você, troca a cada série', false, 'intermediario'),
('Barra Fixa Peito na Barra', 'costas', 'composto', 'peso corporal', '4', '5-6', '2min', 'Puxa até o peito tocar a barra', false, 'avancado'),
('Barra Fixa em L', 'costas', 'composto', 'peso corporal', '4', '4-6', '2min', 'Pernas estendidas à frente durante a puxada', false, 'avancado'),
('Barra Fixa Máquina de Escrever', 'costas', 'composto', 'peso corporal', '4', '4-6', '2min', 'No topo, desliza de uma mão à outra', false, 'avancado'),
('Barra Fixa Isométrica a 90°', 'costas', 'isolado', 'peso corporal', '3', '15-20s', '60s', 'Segura com os cotovelos a 90°', false, 'intermediario'),
('Skin the Cat', 'costas', 'composto', 'peso corporal', '3', '3-5', '90s', 'Pendurado, passa as pernas entre os braços e volta', false, 'avancado'),
('Puxada na Máquina', 'costas', 'composto', 'máquina', '4', '8-10', '90s', 'Coxas presas, puxa as alças até os ombros', false, 'iniciante'),
('Puxada Unilateral Articulada', 'costas', 'composto', 'máquina', '4', '8-10', '90s', 'Um braço por vez, alonga bem no topo', false, 'iniciante'),
('Remada Baixa com Corda', 'costas', 'composto', 'polia', '4', '8-10', '90s', 'Abre a corda e leva as mãos às costelas', false, 'iniciante'),
('Remada Curvada Unilateral na Polia', 'costas', 'composto', 'polia', '4', '8-10', '90s', 'Tronco inclinado de frente pra polia baixa', false, 'iniciante'),
('Remada no Banco Inclinado na Polia', 'costas', 'composto', 'polia', '4', '8-10', '90s', 'Peito no banco de frente pra polia baixa', false, 'iniciante'),
('Remada Curvada com Barra Hexagonal', 'costas', 'composto', 'barra', '4', '8-10', '90s', 'Dentro da barra, pegada neutra', false, 'intermediario'),
('Remada Invertida com Pegada Aberta', 'costas', 'composto', 'peso corporal', '4', '8-10', '90s', 'Mãos além dos ombros, cotovelos abertos', false, 'iniciante'),
('Remada Invertida Unilateral', 'costas', 'composto', 'peso corporal', '4', '5-6 cada lado', '90s', 'Um braço só, quadril não gira', false, 'avancado'),
('Levantamento Terra de Mala', 'costas', 'composto', 'kettlebell', '4', '8-10 cada lado', '90s', 'Peso de um lado só, tronco não inclina', false, 'intermediario'),
('Levantamento Terra Jefferson', 'costas', 'composto', 'barra', '4', '6-8', '2min', 'Uma perna de cada lado da barra', false, 'avancado'),
('Power Clean', 'costas', 'composto', 'barra', '5', '3', '2min', 'Do chão aos ombros, recebe com os joelhos semiflexionados', false, 'avancado'),
('Hang Clean', 'costas', 'composto', 'barra', '5', '3', '2min', 'Parte da altura dos joelhos, extensão explosiva do quadril', false, 'avancado'),
('Clean com Halteres', 'costas', 'composto', 'halteres', '4', '6-8', '90s', 'Halteres saem da lateral das pernas até os ombros', false, 'intermediario'),
('Puxada Alta Olímpica', 'costas', 'composto', 'barra', '4', '5', '2min', 'Estende o quadril e puxa a barra até o peito', false, 'avancado'),
('Hiperextensão Lombar Unilateral', 'costas', 'isolado', 'peso corporal', '3', '8-10 cada perna', '45s', 'Uma perna presa, a outra solta', false, 'intermediario'),
('Hiperextensão com Rotação', 'costas', 'isolado', 'peso corporal', '3', '8 cada lado', '45s', 'No topo, gira o tronco pra um lado', false, 'intermediario'),
('Hiperextensão Isométrica', 'costas', 'isolado', 'peso corporal', '3', '30s', '45s', 'Segura com o tronco alinhado às pernas', false, 'iniciante'),
('Nadador no Solo', 'costas', 'isolado', 'peso corporal', '3', '30s', '30s', 'De bruços, alterna braço e perna opostos', false, 'iniciante'),
('Retração Escapular na Polia', 'costas', 'isolado', 'polia', '3', '12-15', '45s', 'Braços estendidos, só as escápulas se juntam', false, 'iniciante'),
('Depressão Escapular na Polia', 'costas', 'isolado', 'polia', '3', '12-15', '45s', 'Braços estendidos, ombros descem longe das orelhas', false, 'iniciante'),
('Encolhimento com Elástico', 'costas', 'isolado', 'elástico', '3', '12-15', '45s', 'Pisa no elástico, sobe os ombros em linha reta', false, 'iniciante'),

-- Ombro
('Desenvolvimento Meio Ajoelhado com Halter', 'ombro', 'composto', 'halteres', '4', '8-10', '90s', 'Um joelho no chão, empurra com o braço do mesmo lado', false, 'iniciante'),
('Desenvolvimento na Bola Suíça', 'ombro', 'composto', 'bola', '4', '8-10', '90s', 'Sentado na bola, core segura o equilíbrio', false, 'intermediario'),
('Desenvolvimento Javelin', 'ombro', 'composto', 'barra', '3', '6-8 cada lado', '90s', 'Segura a barra pelo meio com uma mão', false, 'avancado'),
('Desenvolvimento com Anilha', 'ombro', 'composto', 'anilha', '3', '10-12', '60s', 'Segura a anilha pelas bordas, empurra acima da cabeça', false, 'iniciante'),
('Push Jerk', 'ombro', 'composto', 'barra', '5', '3', '2min', 'Impulso das pernas e entra embaixo da barra', false, 'avancado'),
('Power Snatch', 'ombro', 'composto', 'barra', '5', '3', '2min', 'Do chão até acima da cabeça, pegada aberta', false, 'avancado'),
('Snatch com Halter', 'ombro', 'composto', 'halteres', '4', '6 cada lado', '90s', 'Do chão até acima da cabeça com um braço', false, 'intermediario'),
('Sustentação de Barra Acima da Cabeça', 'ombro', 'isolado', 'barra', '3', '20-30s', '60s', 'Cotovelos travados, costelas fechadas', false, 'intermediario'),
('Toque no Ombro em Parada de Mão', 'ombro', 'isolado', 'peso corporal', '3', '6 cada lado', '90s', 'De frente pra parede, alterna o peso entre as mãos', false, 'avancado'),
('Caminhada do Caranguejo', 'ombro', 'composto', 'peso corporal', '3', '10m', '45s', 'De barriga pra cima, quadril alto, anda com mãos e pés', false, 'iniciante'),
('Elevação Lateral na Polia por Trás', 'ombro', 'isolado', 'polia', '3', '12-15', '45s', 'Cabo passa atrás do corpo, mais alongamento', false, 'iniciante'),
('Elevação Lateral com Cotovelos Flexionados', 'ombro', 'isolado', 'halteres', '3', '12-15', '45s', 'Cotovelos a 90°, permite mais carga', false, 'iniciante'),
('Elevação Frontal com Kettlebell', 'ombro', 'isolado', 'kettlebell', '3', '12-15', '45s', 'Segura a alça com as duas mãos, sobe até os olhos', false, 'iniciante'),
('Elevação em 6 Tempos', 'ombro', 'isolado', 'halteres', '3', '8', '60s', 'Lateral, frente e acima da cabeça, e volta pelo mesmo caminho', false, 'intermediario'),
('Crucifixo Invertido Deitado de Lado', 'ombro', 'isolado', 'halteres', '3', '12-15', '45s', 'Deitado de lado, braço sobe da frente até o teto', false, 'iniciante'),
('Remada Unilateral para Deltoide Posterior', 'ombro', 'composto', 'halteres', '4', '8-10', '90s', 'Cotovelo aberto a 90° do tronco', false, 'iniciante'),
('Rotação Externa com Cotovelo no Joelho', 'ombro', 'isolado', 'halteres', '3', '12-15', '45s', 'Sentado, cotovelo apoiado no joelho', false, 'iniciante'),
('Elevação Trap-3', 'ombro', 'isolado', 'halteres', '3', '12-15', '45s', 'Curvado, braço sobe na diagonal com o polegar pra cima', false, 'iniciante'),
('Powell Raise', 'ombro', 'isolado', 'halteres', '3', '12-15', '45s', 'Deitado de lado no banco inclinado, braço cruza e sobe', false, 'intermediario'),

-- Bíceps
('Rosca Concentrada Martelo', 'biceps', 'isolado', 'halteres', '3', '12-15', '45s', 'Cotovelo na coxa, pegada neutra', false, 'iniciante'),
('Rosca Drag na Polia', 'biceps', 'isolado', 'polia', '3', '12-15', '45s', 'Barra sobe rente ao tronco, cotovelos vão pra trás', false, 'iniciante'),
('Rosca Deitado no Banco Reto', 'biceps', 'isolado', 'halteres', '3', '12-15', '45s', 'Deitado, braços pendurados abaixo do banco', false, 'intermediario'),
('Rosca Sentado com Barra', 'biceps', 'isolado', 'barra', '3', '12-15', '45s', 'A barra parte das coxas, só a metade de cima', false, 'intermediario'),
('Rosca Scott Unilateral na Máquina', 'biceps', 'isolado', 'máquina', '3', '12-15', '45s', 'Um braço por vez, desce devagar', false, 'iniciante'),
('Rosca com Barra Suíça', 'biceps', 'isolado', 'barra', '3', '12-15', '45s', 'Pegada neutra na barra, punhos retos', false, 'iniciante'),

-- Tríceps
('Tríceps Coice com Peito Apoiado', 'triceps', 'isolado', 'halteres', '3', '12-15', '45s', 'Peito no banco inclinado, os dois braços juntos', false, 'iniciante'),
('Tríceps Testa com Kettlebells', 'triceps', 'isolado', 'kettlebell', '3', '12-15', '45s', 'Kettlebells descem ao lado da cabeça', false, 'intermediario'),
('Tríceps Testa com Elástico', 'triceps', 'isolado', 'elástico', '3', '12-15', '45s', 'Deitado, elástico preso atrás da cabeça', false, 'iniciante'),
('Tríceps Testa no Solo', 'triceps', 'isolado', 'barra', '3', '12-15', '45s', 'A barra pousa no chão atrás da cabeça a cada repetição', false, 'intermediario'),
('Tríceps Deitado de Lado com Halter', 'triceps', 'isolado', 'halteres', '3', '12-15', '45s', 'Deitado de lado, halter desce em direção ao chão', false, 'iniciante'),
('Supino Fechado no Solo', 'triceps', 'composto', 'barra', '4', '8-10', '90s', 'Cotovelos pousam no chão, pegada fechada', false, 'intermediario'),
('Flexão Diamante com Joelhos Apoiados', 'triceps', 'composto', 'peso corporal', '3', '8-10', '60s', 'Joelhos no chão, mãos em losango', false, 'iniciante'),
('Paralelas na Barra Reta', 'triceps', 'composto', 'peso corporal', '4', '6-8', '2min', 'Mãos na barra à frente do quadril, tronco inclina', false, 'avancado'),
('Mergulho Coreano', 'triceps', 'composto', 'peso corporal', '4', '4-6', '2min', 'Barra atrás do corpo, desce com controle', false, 'avancado'),

-- Antebraço
('Rosca de Punho com Elástico', 'antebraco', 'isolado', 'elástico', '3', '15-20', '45s', 'Pisa no elástico, antebraço apoiado na coxa', false, 'iniciante'),
('Flexão na Ponta dos Dedos', 'antebraco', 'composto', 'peso corporal', '3', '6-8', '90s', 'Apoio só nas pontas dos dedos', false, 'avancado'),
('Carregada com Pinça', 'antebraco', 'isolado', 'anilha', '3', '20m', '60s', 'Caminha segurando as anilhas com a ponta dos dedos', false, 'intermediario'),
('Sustentação com Uma Mão na Barra', 'antebraco', 'isolado', 'peso corporal', '3', '10-15s cada lado', '60s', 'Pendurado por um braço, ombro encaixado', false, 'avancado'),
('Farmer Walk com Barra Hexagonal', 'antebraco', 'isolado', 'barra', '3', '20m', '90s', 'Dentro da barra, passos curtos', false, 'intermediario'),

-- Quadríceps
('Agachamento Anderson', 'quadriceps', 'composto', 'barra', '4', '4-6', '2min', 'A barra parte dos pinos, no fundo do agachamento', false, 'avancado'),
('Agachamento Sumô sem Peso', 'quadriceps', 'composto', 'peso corporal', '3', '15-20', '60s', 'Base larga, pontas dos pés pra fora', false, 'iniciante'),
('Agachamento Unilateral no Banco', 'quadriceps', 'composto', 'peso corporal', '3', '6-8 cada perna', '90s', 'Senta no banco com uma perna só e sobe', false, 'intermediario'),
('Agachamento Frontal com Um Kettlebell', 'quadriceps', 'composto', 'kettlebell', '4', '8-10 cada lado', '90s', 'Kettlebell em rack de um lado só, tronco reto', false, 'intermediario'),
('Agachamento com Anilha Acima da Cabeça', 'quadriceps', 'composto', 'anilha', '3', '10-12', '75s', 'Anilha travada acima da cabeça', false, 'intermediario'),
('Agachamento Isométrico com Anilha', 'quadriceps', 'isolado', 'anilha', '3', '40s', '45s', 'Costas na parede, anilha sobre as coxas', false, 'intermediario'),
('Afundo Estático com Barra', 'quadriceps', 'composto', 'barra', '4', '8-10', '90s', 'Barra nas costas, base fixa', false, 'intermediario'),
('Afundo com Pé da Frente Elevado', 'quadriceps', 'composto', 'halteres', '4', '8-10', '90s', 'Pé da frente num step, joelho avança', false, 'iniciante'),
('Afundo Búlgaro na Fita de Suspensão', 'quadriceps', 'composto', 'fita de suspensão', '3', '8-10 cada perna', '90s', 'Pé de trás na alça', false, 'intermediario'),
('Afundo Reverso Landmine', 'quadriceps', 'composto', 'barra', '4', '8-10', '90s', 'Segura a ponta da barra no peito, passo pra trás', false, 'iniciante'),
('Afundo Caminhando com Halteres Acima da Cabeça', 'quadriceps', 'composto', 'halteres', '4', '8-10', '90s', 'Braços travados acima da cabeça', false, 'avancado'),
('Afundo Relógio', 'quadriceps', 'composto', 'peso corporal', '3', '6 cada perna', '60s', 'Passos à frente, pro lado e pra trás em sequência', false, 'iniciante'),
('Afundo com Rotação de Tronco', 'quadriceps', 'composto', 'medicine ball', '3', '10 cada perna', '60s', 'No fundo do afundo, gira pro lado da perna da frente', false, 'iniciante'),
('Step-Up com Elevação de Joelho', 'quadriceps', 'composto', 'halteres', '4', '8-10', '90s', 'No topo, o joelho de trás sobe ao quadril', false, 'iniciante'),
('Step-Up Cruzado', 'quadriceps', 'composto', 'halteres', '4', '8-10', '90s', 'De lado pro banco, a perna de fora cruza e sobe', false, 'intermediario'),
('Salto em Profundidade', 'quadriceps', 'composto', 'peso corporal', '4', '4-5', '2min', 'Cai do caixote e salta assim que toca o chão', false, 'avancado'),
('Salto Unilateral no Caixote', 'quadriceps', 'composto', 'peso corporal', '4', '4-5 cada perna', '90s', 'Salta e aterrissa na mesma perna, caixote baixo', false, 'avancado'),
('Arrasto de Trenó de Frente', 'quadriceps', 'composto', 'trenó', '4', '20m', '90s', 'Cinto preso ao trenó, caminha inclinado à frente', false, 'iniciante'),
('Andar de Pato', 'quadriceps', 'composto', 'peso corporal', '3', '10m', '60s', 'Caminha agachado sem levantar o quadril', false, 'intermediario'),
('Isometria na Cadeira Extensora', 'quadriceps', 'isolado', 'máquina', '3', '20-30s', '45s', 'Segura com os joelhos estendidos', false, 'iniciante'),
('Adução em Pé na Máquina', 'quadriceps', 'isolado', 'máquina', '3', '12-15 cada perna', '45s', 'Em pé, a perna fecha contra o apoio', false, 'iniciante'),
('Adução em Pé com Elástico', 'quadriceps', 'isolado', 'elástico', '3', '15 cada perna', '30s', 'Elástico preso ao lado, a perna cruza à frente', false, 'iniciante'),
('Flexão de Quadril na Polia', 'quadriceps', 'isolado', 'polia', '3', '12-15 cada perna', '45s', 'De costas pra polia baixa, o joelho sobe ao quadril', false, 'iniciante'),
('Flexão de Quadril com Elástico', 'quadriceps', 'isolado', 'elástico', '3', '12 cada perna', '30s', 'Mini band nos pés, um joelho sobe por vez', false, 'iniciante'),

-- Posterior de coxa
('Stiff no Smith', 'posterior_coxa', 'composto', 'máquina', '4', '8-10', '90s', 'Barra guiada, pernas quase estendidas', false, 'iniciante'),
('Stiff Unilateral sem Peso', 'posterior_coxa', 'composto', 'peso corporal', '3', '10 cada perna', '60s', 'Braços à frente, tronco e perna de trás em linha', false, 'iniciante'),
('Stiff Unilateral com Kettlebell', 'posterior_coxa', 'composto', 'kettlebell', '4', '8-10 cada perna', '90s', 'Kettlebell na mão oposta à perna de apoio', false, 'intermediario'),
('Stiff Unilateral com Barra', 'posterior_coxa', 'composto', 'barra', '4', '6-8 cada perna', '90s', 'Uma perna de apoio, barra rente à canela', false, 'avancado'),
('Stiff Unilateral Landmine', 'posterior_coxa', 'composto', 'barra', '4', '8-10 cada perna', '90s', 'Segura a ponta da barra, o arco guia o movimento', false, 'intermediario'),
('Romeno com Dois Kettlebells', 'posterior_coxa', 'composto', 'kettlebell', '4', '8-10', '90s', 'Kettlebells ao lado das pernas, quadril vai pra trás', false, 'iniciante'),
('Good Morning com Halter', 'posterior_coxa', 'composto', 'halteres', '3', '12-15', '60s', 'Halter abraçado no peito, quadril vai pra trás', false, 'iniciante'),
('Flexora Nórdica Excêntrica', 'posterior_coxa', 'composto', 'peso corporal', '3', '5-6', '90s', 'Só a descida em 5s, volta empurrando com as mãos', false, 'intermediario'),
('Flexora Unilateral com Deslizamento', 'posterior_coxa', 'isolado', 'peso corporal', '3', '6-8 cada perna', '60s', 'Um calcanhar desliza, a outra perna no ar', false, 'avancado'),
('Flexora Sentado com Elástico', 'posterior_coxa', 'isolado', 'elástico', '3', '15 cada perna', '45s', 'Elástico preso à frente, calcanhar vai pra baixo do banco', false, 'iniciante'),
('Flexora em Pé com Elástico', 'posterior_coxa', 'isolado', 'elástico', '3', '15 cada perna', '45s', 'Elástico nos tornozelos, calcanhar sobe ao glúteo', false, 'iniciante'),
('Swing com Halter', 'posterior_coxa', 'composto', 'halteres', '4', '15', '60s', 'Segura o halter pela cabeça com as duas mãos', false, 'iniciante'),
('Kettlebell Swing Americano', 'posterior_coxa', 'composto', 'kettlebell', '4', '12', '75s', 'O kettlebell sobe até acima da cabeça', false, 'avancado'),
('Kettlebell Clean', 'posterior_coxa', 'composto', 'kettlebell', '4', '8 cada lado', '75s', 'Do balanço até a posição de rack, sem bater no punho', false, 'intermediario'),

-- Glúteos
('Elevação Pélvica com Kettlebell', 'gluteos', 'composto', 'kettlebell', '4', '8-10', '90s', 'Kettlebell sobre o quadril, costas no banco', false, 'iniciante'),
('Ponte de Glúteo com Halter', 'gluteos', 'composto', 'halteres', '3', '12-15', '60s', 'Costas no chão, halter sobre o quadril', false, 'iniciante'),
('Ponte de Glúteo com Pés na Bola Suíça', 'gluteos', 'isolado', 'bola', '3', '12-15', '45s', 'Calcanhares na bola, quadril sobe sem a bola rolar', false, 'iniciante'),
('Coice em 4 Apoios sem Peso', 'gluteos', 'isolado', 'peso corporal', '3', '15-20 cada perna', '30s', 'Joelho a 90°, a sola do pé sobe ao teto', false, 'iniciante'),
('Coice Diagonal na Polia', 'gluteos', 'isolado', 'polia', '3', '12-15 cada perna', '45s', 'A perna vai pra trás e pra fora a 45°', false, 'iniciante'),
('Abdução em Pé com Caneleira', 'gluteos', 'isolado', 'caneleira', '3', '15-20 cada perna', '30s', 'Apoiado, a perna abre sem o tronco inclinar', false, 'iniciante'),
('Hidrante com Mini Band', 'gluteos', 'isolado', 'elástico', '3', '15 cada perna', '30s', 'Mini band nos joelhos, abre pro lado', false, 'iniciante'),
('Ostra Reversa', 'gluteos', 'isolado', 'peso corporal', '3', '15 cada lado', '30s', 'Deitado de lado, joelhos juntos, o pé de cima sobe', false, 'iniciante'),
('Ostra em Prancha Lateral', 'gluteos', 'isolado', 'peso corporal', '3', '10-12 cada lado', '45s', 'Prancha lateral de joelhos, abre o joelho de cima', false, 'intermediario'),
('Agachamento com Mini Band', 'gluteos', 'composto', 'elástico', '3', '15-20', '60s', 'Mini band acima dos joelhos, empurra pra fora', false, 'iniciante'),
('Agachamento Ajoelhado', 'gluteos', 'composto', 'barra', '4', '10-12', '75s', 'Ajoelhado, senta nos calcanhares e estende o quadril', false, 'intermediario'),
('Extensão de Quadril Ajoelhado com Elástico', 'gluteos', 'composto', 'elástico', '3', '15-20', '45s', 'Elástico no quadril preso atrás, ajoelhado', false, 'iniciante'),
('Avião de Quadril', 'gluteos', 'isolado', 'peso corporal', '3', '5 cada lado', '60s', 'Numa perna só, o quadril abre e fecha', false, 'avancado'),

-- Panturrilha
('Panturrilha no Solo', 'panturrilha', 'isolado', 'peso corporal', '3', '20', '30s', 'Sem step, sobe na ponta dos pés e segura 1s', false, 'iniciante'),
('Panturrilha em Pé com Kettlebell', 'panturrilha', 'isolado', 'kettlebell', '3', '12-15', '45s', 'Kettlebell numa mão, a outra apoia', false, 'iniciante'),
('Panturrilha em Pé com Elástico', 'panturrilha', 'isolado', 'elástico', '3', '15-20', '30s', 'Pisa no elástico e leva as alças aos ombros', false, 'iniciante'),
('Panturrilha Agachado (Sóleo)', 'panturrilha', 'isolado', 'peso corporal', '3', '15-20', '30s', 'Meio agachado, os calcanhares sobem e descem', false, 'iniciante'),
('Saltitos Unilaterais na Ponta do Pé', 'panturrilha', 'isolado', 'peso corporal', '3', '12 cada perna', '45s', 'Uma perna, contato rápido com o chão', false, 'intermediario'),
('Caminhada nos Calcanhares', 'panturrilha', 'isolado', 'peso corporal', '3', '20m', '30s', 'Ponta dos pés pra cima o tempo todo', false, 'iniciante'),

-- Abdômen e core (pós-treino)
('Prancha com Elevação de Braço', 'core', 'isolado', 'peso corporal', '3', '10 cada lado', '30s', 'Um braço estende à frente, quadril não gira', true, 'iniciante'),
('Prancha com Braço e Perna Opostos', 'core', 'isolado', 'peso corporal', '3', '6 cada lado', '45s', 'Só uma mão e o pé oposto no chão', true, 'avancado'),
('Prancha com Giro de Quadril', 'core', 'isolado', 'peso corporal', '3', '12 cada lado', '30s', 'O quadril gira e quase toca o chão de cada lado', true, 'iniciante'),
('Prancha Caminhando de Lado', 'core', 'isolado', 'peso corporal', '3', '6 passos cada lado', '45s', 'Mão e pé do mesmo lado avançam juntos', true, 'intermediario'),
('Prancha com Elevação de Quadril', 'core', 'isolado', 'peso corporal', '3', '10-12', '30s', 'Da prancha, o quadril sobe ao teto e volta', true, 'iniciante'),
('Prancha Urso com Toque no Ombro', 'core', 'isolado', 'peso corporal', '3', '10 cada lado', '45s', 'Joelhos a 5cm do chão, a mão toca o ombro oposto', true, 'intermediario'),
('Prancha na Fita de Suspensão', 'core', 'isolado', 'fita de suspensão', '3', '30s', '45s', 'Pés nas alças, antebraços no chão', true, 'intermediario'),
('Prancha com Pés na Bola Suíça', 'core', 'isolado', 'bola', '3', '30s', '45s', 'Mãos no chão, canelas na bola', true, 'intermediario'),
('Prancha Lateral com Remada na Polia', 'core', 'isolado', 'polia', '3', '8-10 cada lado', '45s', 'Em prancha lateral, o braço de cima rema', true, 'avancado'),
('Prancha Reversa com Elevação de Perna', 'core', 'isolado', 'peso corporal', '3', '8 cada perna', '45s', 'Quadril alto, uma perna sobe por vez', true, 'intermediario'),
('Caranguejo com Toque no Pé', 'core', 'isolado', 'peso corporal', '3', '10 cada lado', '30s', 'De barriga pra cima, a mão toca o pé oposto no alto', true, 'iniciante'),
('Abdominal com Anilha Acima da Cabeça', 'core', 'isolado', 'anilha', '3', '12-15', '45s', 'Braços estendidos pro teto, a anilha sobe reto', true, 'intermediario'),
('Abdominal com Elástico', 'core', 'isolado', 'elástico', '3', '15-20', '30s', 'Elástico preso atrás da cabeça, enrola o tronco', true, 'iniciante'),
('Abdominal Grupado', 'core', 'isolado', 'peso corporal', '3', '15-20', '30s', 'Ombros e joelhos se encontram no meio', true, 'iniciante'),
('Abdominal Estrela', 'core', 'isolado', 'peso corporal', '3', '10 cada lado', '30s', 'Braços e pernas abertos, a mão busca o pé oposto', true, 'iniciante'),
('Abdominal Sprinter', 'core', 'isolado', 'peso corporal', '3', '10 cada lado', '45s', 'Sobe levando um joelho ao peito, como numa corrida', true, 'intermediario'),
('Abdominal Canivete Lateral', 'core', 'isolado', 'peso corporal', '3', '10-12 cada lado', '45s', 'Deitado de lado, tronco e pernas sobem juntos', true, 'intermediario'),
('Abdominal Infra Declinado', 'core', 'isolado', 'peso corporal', '3', '10-12', '45s', 'Cabeça no alto do banco declinado, o quadril sobe', true, 'intermediario'),
('Abdominal Infra na Polia', 'core', 'isolado', 'polia', '3', '12-15', '45s', 'Caneleiras da polia nos pés, joelhos ao peito', true, 'intermediario'),
('Abdominal no GHD', 'core', 'isolado', 'máquina', '3', '8-10', '60s', 'Pés presos, o tronco desce abaixo do quadril', true, 'avancado'),
('Abdominal com Arremesso de Medicine Ball', 'core', 'isolado', 'medicine ball', '3', '10-12', '45s', 'Sobe e arremessa a bola na parede', true, 'intermediario'),
('Abdominal Lateral na Bola Suíça', 'core', 'isolado', 'bola', '3', '12-15 cada lado', '30s', 'De lado na bola, pés apoiados na parede', true, 'iniciante'),
('Russian Twist na Bola Suíça', 'core', 'isolado', 'bola', '3', '10 cada lado', '45s', 'Ombros na bola, os braços giram de um lado ao outro', true, 'intermediario'),
('Descida Alternada de Pernas', 'core', 'isolado', 'peso corporal', '3', '10 cada perna', '30s', 'Pernas pro teto, uma desce por vez', true, 'iniciante'),
('Círculos de Pernas Deitado', 'core', 'isolado', 'peso corporal', '3', '8 cada lado', '45s', 'Pernas juntas desenham círculos, lombar no chão', true, 'intermediario'),
('Elevação de Joelhos Oblíqua Pendurado', 'core', 'isolado', 'peso corporal', '3', '8 cada lado', '45s', 'Os joelhos sobem em direção a um ombro', true, 'intermediario'),
('Sustentação em L Pendurado', 'core', 'isolado', 'peso corporal', '3', '10-15s', '60s', 'Pendurado, pernas estendidas na horizontal', true, 'intermediario'),
('Canoa Grupada', 'core', 'isolado', 'peso corporal', '3', '30s', '30s', 'Joelhos dobrados, lombar colada no chão', true, 'iniciante'),
('Barco Isométrico', 'core', 'isolado', 'peso corporal', '3', '30s', '30s', 'Sentado em V, peito aberto', true, 'iniciante'),
('Dead Bug com Peso', 'core', 'isolado', 'halteres', '3', '8 cada lado', '45s', 'Halter nas mãos acima do peito', true, 'intermediario'),
('Dead Bug com Toque de Calcanhar', 'core', 'isolado', 'peso corporal', '3', '10 cada lado', '30s', 'Joelhos a 90°, um calcanhar toca o chão por vez', true, 'iniciante'),
('Bird Dog com Cotovelo ao Joelho', 'core', 'isolado', 'peso corporal', '3', '10 cada lado', '30s', 'Cotovelo e joelho opostos se tocam sob o tronco', true, 'iniciante'),
('Rotação de Tronco com Elástico', 'core', 'isolado', 'elástico', '3', '12 cada lado', '45s', 'Elástico preso ao lado, braços estendidos giram', true, 'iniciante'),
('Lenhador com Medicine Ball', 'core', 'isolado', 'medicine ball', '3', '12 cada lado', '45s', 'Da lateral do joelho até acima do ombro oposto', true, 'iniciante'),
('Pallof Isométrico', 'core', 'isolado', 'polia', '3', '20s cada lado', '30s', 'Braços estendidos à frente, segura sem girar', true, 'iniciante'),
('Pallof Press Acima da Cabeça', 'core', 'isolado', 'polia', '3', '8 cada lado', '45s', 'Estende à frente e leva acima da cabeça', true, 'intermediario'),
('Roda Abdominal na Diagonal', 'core', 'isolado', 'peso corporal', '3', '6 cada lado', '60s', 'A roda avança a 45° pra cada lado', true, 'intermediario'),
('Rollout com Deslizamento', 'core', 'isolado', 'peso corporal', '3', '8-10', '60s', 'Mãos deslizam à frente, joelhos no chão', true, 'intermediario'),
('Pike com Deslizamento', 'core', 'isolado', 'peso corporal', '3', '8-10', '60s', 'Pés deslizam em direção às mãos, pernas estendidas', true, 'intermediario'),
('Mountain Climber com Deslizamento', 'core', 'isolado', 'peso corporal', '3', '30s', '30s', 'Pés deslizam alternados, quadril baixo', true, 'iniciante'),
('Mountain Climber na Fita de Suspensão', 'core', 'isolado', 'fita de suspensão', '3', '30s', '45s', 'Pés nas alças, joelhos alternam ao peito', true, 'intermediario'),
('Marcha com Peso', 'core', 'isolado', 'halteres', '3', '30s', '45s', 'Parado no lugar, joelhos sobem ao quadril', true, 'iniciante'),
('Carregada Frontal com Kettlebells', 'core', 'isolado', 'kettlebell', '3', '20m', '60s', 'Kettlebells em rack, cotovelos baixos', true, 'intermediario'),
('Carregada Zercher', 'core', 'isolado', 'barra', '3', '20m', '90s', 'Barra na dobra dos cotovelos, tronco ereto', true, 'avancado'),
('Meio Levantamento Turco', 'core', 'isolado', 'kettlebell', '3', '5 cada lado', '60s', 'Do chão até sentar apoiado na mão', true, 'intermediario'),

-- Cardio (pós-treino)
('Caminhada e Corrida Alternadas', 'cardio', 'cardio', 'peso corporal', '-', '24min', '-', '1min correndo / 2min caminhando', true, 'iniciante'),
('Corrida de Ritmo', 'cardio', 'cardio', 'peso corporal', '-', '20min', '-', 'Ritmo forte que dá pra sustentar', true, 'intermediario'),
('Tiros de 400m', 'cardio', 'cardio', 'peso corporal', '-', '6x400m', '2min', 'Volta na pista em ritmo forte, recupera caminhando', true, 'intermediario'),
('Corrida em Trilha', 'cardio', 'cardio', 'peso corporal', '-', '30min', '-', 'Passos curtos na subida, olhar no terreno', true, 'intermediario'),
('Corrida na Areia', 'cardio', 'cardio', 'peso corporal', '-', '15min', '-', 'Areia fofa, passadas curtas', true, 'intermediario'),
('Corrida de Costas', 'cardio', 'cardio', 'peso corporal', '-', '8x20m', '40s', 'Ponta dos pés, olha por cima do ombro', true, 'iniciante'),
('Tiros em Escadaria', 'cardio', 'cardio', 'peso corporal', '-', '8x20s forte', '60s', 'Sobe correndo, desce caminhando', true, 'intermediario'),
('Esteira — Corrida Inclinada', 'cardio', 'cardio', 'máquina', '-', '15min', '-', '4-6% de inclinação, passadas curtas', true, 'intermediario'),
('Esteira Desligada', 'cardio', 'cardio', 'máquina', '-', '8x20s forte', '60s', 'Esteira desligada, empurra a lona com as pernas', true, 'avancado'),
('Caminhada Nórdica', 'cardio', 'cardio', 'peso corporal', '-', '40min', '-', 'Bastões empurram o chão a cada passo', true, 'iniciante'),
('Caminhada na Piscina', 'cardio', 'cardio', 'piscina', '-', '20min', '-', 'Água na cintura, passos largos', true, 'iniciante'),
('Bicicleta — Subida', 'cardio', 'cardio', 'máquina', '-', '6x3min', '2min', 'Carga alta, cadência baixa, pode pedalar em pé', true, 'intermediario'),
('Patins', 'cardio', 'cardio', 'peso corporal', '-', '30min', '-', 'Joelhos flexionados, empurra pro lado', true, 'iniciante'),
('Caiaque', 'cardio', 'cardio', 'peso corporal', '-', '30min', '-', 'A remada vem do giro do tronco', true, 'iniciante'),
('Stand Up Paddle', 'cardio', 'cardio', 'peso corporal', '-', '30min', '-', 'Joelhos soltos, o core segura o equilíbrio', true, 'iniciante'),
('Escalada Indoor', 'cardio', 'cardio', 'peso corporal', '-', '40min', '-', 'Empurra com as pernas, braços estendidos', true, 'intermediario'),
('Simulador de Escalada', 'cardio', 'cardio', 'máquina', '-', '10x30s', '30s', 'Braço e perna opostos sobem juntos', true, 'intermediario'),
('Mini Trampolim', 'cardio', 'cardio', 'peso corporal', '-', '15min', '-', 'Saltos baixos e contínuos', true, 'iniciante'),
('Pular Corda Cruzado', 'cardio', 'cardio', 'peso corporal', '-', '8x30s', '30s', 'Cruza os braços a cada dois saltos', true, 'intermediario'),
('Pular Corda com Joelhos Altos', 'cardio', 'cardio', 'peso corporal', '-', '8x30s', '30s', 'Corre no lugar passando a corda', true, 'intermediario'),
('Pular Corda com Um Pé', 'cardio', 'cardio', 'peso corporal', '-', '8x30s', '30s', 'Troca de pé a cada 10 saltos', true, 'intermediario'),
('Corda Naval — Círculos', 'cardio', 'cardio', 'peso corporal', '-', '8x20s', '40s', 'Os braços desenham círculos pra fora e pra dentro', true, 'intermediario'),
('Corda Naval com Polichinelo', 'cardio', 'cardio', 'peso corporal', '-', '8x20s', '40s', 'Abre braços e pernas segurando as cordas', true, 'intermediario'),
('Burpee Lateral sobre a Barra', 'cardio', 'cardio', 'peso corporal', '-', '5x45s', '45s', 'Salta de lado por cima da barra a cada repetição', true, 'intermediario'),
('Burpee com Barra Fixa', 'cardio', 'cardio', 'peso corporal', '-', '5x45s', '60s', 'O salto do burpee emenda numa barra fixa', true, 'avancado'),
('Polichinelo com Agachamento', 'cardio', 'cardio', 'peso corporal', '-', '8x20s', '40s', 'Abre os pés caindo em agachamento', true, 'intermediario'),
('Saltos Laterais sobre a Linha', 'cardio', 'cardio', 'peso corporal', '-', '8x20s', '40s', 'Pés juntos, saltos curtos e rápidos', true, 'iniciante'),
('Toques Alternados no Step', 'cardio', 'cardio', 'peso corporal', '-', '8x30s', '30s', 'A ponta de um pé toca o step por vez', true, 'iniciante'),
('Chutes Frontais Alternados', 'cardio', 'cardio', 'peso corporal', '-', '8x30s', '30s', 'Chuta à altura do quadril, guarda alta', true, 'iniciante'),
('Sprint com Trenó', 'cardio', 'cardio', 'trenó', '-', '6x15m', '90s', 'Carga leve, corre empurrando o trenó', true, 'avancado'),
('Puxada de Trenó com Corda', 'cardio', 'cardio', 'trenó', '-', '6x15m', '60s', 'Parado, puxa o trenó mão sobre mão', true, 'intermediario'),

-- Mobilidade e alongamento (pós-treino)
('Alongamento de Peitoral no Solo', 'mobilidade', 'isolado', 'peso corporal', '2', '30s cada lado', '-', 'De bruços, braço aberto, gira o corpo pro outro lado', true, 'iniciante'),
('Alongamento do Dorminhoco', 'mobilidade', 'isolado', 'peso corporal', '2', '30s cada lado', '-', 'Deitado de lado, empurra o antebraço em direção ao chão', true, 'iniciante'),
('Alongamento do Elevador da Escápula', 'mobilidade', 'isolado', 'peso corporal', '2', '20s cada lado', '-', 'Olha pra axila e puxa a cabeça de leve', true, 'iniciante'),
('Rotação de Pescoço', 'mobilidade', 'isolado', 'peso corporal', '2', '8 cada lado', '-', 'Gira a cabeça devagar de um ombro ao outro', true, 'iniciante'),
('Abraço e Abertura de Braços', 'mobilidade', 'isolado', 'peso corporal', '2', '12', '-', 'Abraça o corpo e abre os braços, alternando', true, 'iniciante'),
('Círculos de Punho', 'mobilidade', 'isolado', 'peso corporal', '2', '10 cada lado', '-', 'Mãos entrelaçadas giram nos dois sentidos', true, 'iniciante'),
('Mobilidade de Punho em 4 Apoios', 'mobilidade', 'isolado', 'peso corporal', '2', '10', '-', 'Mãos no chão, balança o corpo pra frente e pra trás', true, 'iniciante'),
('Agulha em 4 Apoios', 'mobilidade', 'isolado', 'peso corporal', '2', '8 cada lado', '-', 'Um braço passa por baixo do tronco até o ombro tocar o chão', true, 'iniciante'),
('Postura do Filhote', 'mobilidade', 'isolado', 'peso corporal', '2', '30s', '-', 'Quadril sobre os joelhos, peito desce ao chão', true, 'iniciante'),
('Postura da Esfinge', 'mobilidade', 'isolado', 'peso corporal', '2', '30s', '-', 'Antebraços no chão, peito à frente', true, 'iniciante'),
('Extensão Torácica no Banco', 'mobilidade', 'isolado', 'peso corporal', '2', '30s', '-', 'Cotovelos no banco, peito desce entre os braços', true, 'iniciante'),
('Rotação de Tronco em Pé', 'mobilidade', 'isolado', 'peso corporal', '2', '10 cada lado', '-', 'Braços soltos, gira de um lado ao outro', true, 'iniciante'),
('Flexão à Frente em Pé', 'mobilidade', 'isolado', 'peso corporal', '2', '30s', '-', 'Joelhos soltos, tronco pendurado', true, 'iniciante'),
('Torção Sentado', 'mobilidade', 'isolado', 'peso corporal', '2', '30s cada lado', '-', 'Uma perna cruzada, gira o tronco pro lado dela', true, 'iniciante'),
('Postura do Bebê Feliz', 'mobilidade', 'isolado', 'peso corporal', '2', '30s', '-', 'Segura os pés, joelhos descem ao lado do tronco', true, 'iniciante'),
('Balanço em 4 Apoios', 'mobilidade', 'isolado', 'peso corporal', '2', '10', '-', 'Coluna neutra, o quadril vai aos calcanhares', true, 'iniciante'),
('Alongamento de Piriforme Sentado', 'mobilidade', 'isolado', 'peso corporal', '2', '30s cada lado', '-', 'Sentado numa cadeira, tornozelo no joelho, inclina à frente', true, 'iniciante'),
('Alongamento de Posterior Deitado', 'mobilidade', 'isolado', 'peso corporal', '2', '30s cada perna', '-', 'Deitado, puxa a perna estendida com uma toalha', true, 'iniciante'),
('Alongamento Afastado Sentado', 'mobilidade', 'isolado', 'peso corporal', '2', '45s', '-', 'Pernas afastadas, o tronco desce ao centro', true, 'intermediario'),
('Alongamento de Adutores em Pé', 'mobilidade', 'isolado', 'peso corporal', '2', '30s cada lado', '-', 'Base larga, dobra um joelho e estende o outro', true, 'iniciante'),
('Alongamento de Quadríceps Deitado de Lado', 'mobilidade', 'isolado', 'peso corporal', '2', '30s cada lado', '-', 'Deitado de lado, puxa o pé de cima ao glúteo', true, 'iniciante'),
('Afundo com Alcance Lateral', 'mobilidade', 'isolado', 'peso corporal', '2', '6 cada lado', '-', 'No afundo, o braço de trás alcança por cima da cabeça', true, 'iniciante'),
('Caminhada do Soldado', 'mobilidade', 'isolado', 'peso corporal', '2', '10 cada perna', '-', 'Chuta a perna estendida até a mão oposta', true, 'iniciante'),
('Caminhada Abraçando o Joelho', 'mobilidade', 'isolado', 'peso corporal', '2', '10 cada perna', '-', 'A cada passo, abraça um joelho no peito', true, 'iniciante'),
('Alongamento de Canela Ajoelhado', 'mobilidade', 'isolado', 'peso corporal', '2', '30s', '-', 'Senta nos calcanhares com o peito dos pés no chão', true, 'iniciante'),
('Alongamento da Fáscia Plantar', 'mobilidade', 'isolado', 'peso corporal', '2', '30s', '-', 'Ajoelhado, dedos dos pés dobrados no chão', true, 'iniciante'),
('Círculos de Tornozelo', 'mobilidade', 'isolado', 'peso corporal', '2', '10 cada lado', '-', 'O pé desenha círculos nos dois sentidos', true, 'iniciante'),
('Liberação Miofascial de Adutores', 'mobilidade', 'isolado', 'rolo', '2', '45s cada perna', '-', 'De bruços, perna aberta, rola a parte interna da coxa', true, 'iniciante'),
('Liberação Miofascial da Lateral da Coxa', 'mobilidade', 'isolado', 'rolo', '2', '45s cada perna', '-', 'Deitado de lado, rola do quadril ao joelho', true, 'iniciante'),
('Liberação Miofascial de Tibial', 'mobilidade', 'isolado', 'rolo', '2', '45s cada perna', '-', 'Ajoelhado sobre o rolo, rola a frente da canela', true, 'iniciante'),
('Respiração Diafragmática', 'mobilidade', 'isolado', 'peso corporal', '2', '10', '-', 'Mão na barriga, inspira pelo nariz e solta devagar', true, 'iniciante')
on conflict (nome) do nothing;
