-- Segunda expansão da biblioteca de exercícios: 544 exercícios novos,
-- somados aos das migrations 20260821020000_exercise_library.sql e
-- 20260925030000_exercise_library_expansao.sql. Só insere; nada do que já
-- existe é alterado.
--
-- Mesmos critérios das anteriores:
-- - nomes reais e sem duplicata disfarçada: histórico de carga e recordes são
--   agrupados pelo nome, e dois nomes pro mesmo exercício partiriam a evolução
--   do usuário. Cada nome novo foi conferido contra a biblioteca e contra os
--   nomes usados nos planos prontos (inclusive pelo inglês, que denuncia
--   sinônimo: "Prancha Alta" = "Prancha com Braços Estendidos" ficou de fora).
--   Variação só de pausa, cadência ou posição dos pés também não entra;
-- - composto 4 × 8-10 / 90s, isolado 3 × 12-15 / 45s, salvo isometrias,
--   exercícios por lado e peso corporal leve;
-- - nivel_minimo: guiados/peso corporal simples no iniciante; livres técnicos
--   e instabilidade no intermediário; explosão, alavanca longa, calistenia
--   avançada ou carga axial alta no avançado.
--
-- Dois grupos novos, ambos fora do sorteio da geração automática (nenhum foco
-- de FOCO_TO_GRUPOS aponta pra eles), disponíveis pra troca de exercício e pro
-- painel:
-- - antebraco: punho e pegada (as roscas inversas novas entram aqui);
-- - mobilidade: alongamento, mobilidade e liberação miofascial, marcados como
--   pós-treino (is_post_workout), como core e cardio.
-- Equipamentos novos: anilha, fita de suspensão, medicine ball, trenó e rolo.
-- Grupo e equipamento novos precisam de rótulo em app-react/scripts/build-site.mjs.
--
-- Todo nome e toda técnica daqui têm inglês em app-react/src/i18n/en/exercises.js
-- (e o nome, na cópia supabase/functions/_shared/exerciseI18n.ts).
--
-- on conflict (nome) do nothing: reaplicar a migration (ou um admin já ter
-- cadastrado algum destes pelo painel) não duplica nem sobrescreve.
insert into public.exercise_library
  (nome, grupo_muscular, tipo, equipamento, series, reps, descanso, tecnica, is_post_workout, nivel_minimo)
values
-- Peito
('Supino Declinado com Halteres', 'peito', 'composto', 'halteres', '4', '8-10', '90s', 'Foco peito inferior, halteres na linha do esterno', false, 'intermediario'),
('Supino Declinado no Smith', 'peito', 'composto', 'máquina', '4', '8-10', '90s', 'Barra guiada desce até o peito inferior', false, 'iniciante'),
('Supino Declinado na Máquina', 'peito', 'composto', 'máquina', '4', '8-10', '90s', 'Empurra pra baixo e pra frente, sem travar os cotovelos', false, 'iniciante'),
('Supino Reto com Pegada Neutra (Halteres)', 'peito', 'composto', 'halteres', '4', '8-10', '90s', 'Palmas se olhando, poupa os ombros', false, 'iniciante'),
('Supino Inclinado com Pegada Neutra (Halteres)', 'peito', 'composto', 'halteres', '4', '8-10', '90s', 'Banco a 30°, palmas se olhando', false, 'iniciante'),
('Supino Unilateral com Halter', 'peito', 'composto', 'halteres', '4', '8-10', '90s', 'Um braço por vez, core trava a rotação', false, 'intermediario'),
('Supino Alternado com Halteres', 'peito', 'composto', 'halteres', '4', '8-10', '90s', 'Um braço sobe enquanto o outro fica estendido', false, 'intermediario'),
('Supino no Solo com Halteres (Floor Press)', 'peito', 'composto', 'halteres', '4', '8-10', '90s', 'Cotovelos tocam o chão de leve a cada repetição', false, 'iniciante'),
('Supino no Solo com Barra (Floor Press)', 'peito', 'composto', 'barra', '4', '8-10', '90s', 'Pausa com os cotovelos no chão, sem quicar', false, 'intermediario'),
('Supino com Pegada Invertida', 'peito', 'composto', 'barra', '4', '8-10', '90s', 'Pegada supinada, barra desce no peito inferior', false, 'avancado'),
('Supino Guilhotina', 'peito', 'composto', 'barra', '4', '8-10', '90s', 'Barra desce na linha do pescoço, carga leve', false, 'avancado'),
('Supino Reto com Pegada Aberta', 'peito', 'composto', 'barra', '4', '8-10', '90s', 'Pegada além dos ombros, amplitude curta', false, 'intermediario'),
('Supino Sentado na Polia', 'peito', 'composto', 'polia', '4', '8-10', '90s', 'Cabos na altura do peito, tensão constante', false, 'iniciante'),
('Supino em Pé na Polia', 'peito', 'composto', 'polia', '4', '8-10', '90s', 'Um pé à frente, tronco firme', false, 'iniciante'),
('Supino Unilateral na Polia', 'peito', 'composto', 'polia', '4', '8-10', '90s', 'Um braço por vez, sem girar o tronco', false, 'iniciante'),
('Supino Inclinado na Polia', 'peito', 'composto', 'polia', '4', '8-10', '90s', 'Banco inclinado entre as polias baixas', false, 'iniciante'),
('Supino Unilateral na Máquina', 'peito', 'composto', 'máquina', '4', '8-10', '90s', 'Um braço por vez, costas coladas no encosto', false, 'iniciante'),
('Supino Reto com Kettlebells', 'peito', 'composto', 'kettlebell', '4', '8-10', '90s', 'Punhos firmes, kettlebell apoiado no antebraço', false, 'intermediario'),
('Supino com Elástico', 'peito', 'composto', 'elástico', '4', '8-10', '90s', 'Elástico preso atrás, empurra à frente do peito', false, 'iniciante'),
('Supino com Halteres na Bola Suíça', 'peito', 'composto', 'bola', '4', '8-10', '90s', 'Ombros na bola, quadril alto', false, 'intermediario'),
('Squeeze Press com Halteres', 'peito', 'composto', 'halteres', '4', '8-10', '90s', 'Halteres colados um no outro o tempo todo', false, 'iniciante'),
('Squeeze Press Inclinado', 'peito', 'composto', 'halteres', '4', '8-10', '90s', 'Halteres colados, banco a 30°', false, 'iniciante'),
('Svend Press com Anilha', 'peito', 'isolado', 'anilha', '3', '12-15', '45s', 'Aperta a anilha entre as palmas e estende os braços', false, 'iniciante'),
('Flexão de Braço com Joelhos Apoiados', 'peito', 'composto', 'peso corporal', '3', '10-12', '60s', 'Joelhos no chão, corpo reto do joelho à cabeça', false, 'iniciante'),
('Flexão de Braço Aberta', 'peito', 'composto', 'peso corporal', '3', '10-12', '60s', 'Mãos além da largura dos ombros', false, 'iniciante'),
('Flexão Arqueiro', 'peito', 'composto', 'peso corporal', '4', '6-8 cada lado', '90s', 'Desce sobre um braço, o outro fica estendido ao lado', false, 'avancado'),
('Flexão com Palmas', 'peito', 'composto', 'peso corporal', '4', '6-8', '90s', 'Empurra explosivo, amortece a queda', false, 'avancado'),
('Flexão com Um Braço', 'peito', 'composto', 'peso corporal', '4', '4-6 cada lado', '2min', 'Pés afastados, quadril sem girar', false, 'avancado'),
('Flexão Hindu', 'peito', 'composto', 'peso corporal', '3', '10-12', '60s', 'Quadril alto, mergulha e sobe olhando à frente', false, 'intermediario'),
('Flexão Mergulho (Dive Bomber)', 'peito', 'composto', 'peso corporal', '3', '8-10', '75s', 'Mergulha e volta pelo mesmo caminho', false, 'avancado'),
('Flexão Spiderman', 'peito', 'composto', 'peso corporal', '3', '8-10 cada lado', '75s', 'Joelho vai ao cotovelo na descida', false, 'intermediario'),
('Flexão com Rotação (T Push-Up)', 'peito', 'composto', 'peso corporal', '3', '8-10 cada lado', '75s', 'No topo, gira e abre um braço pro teto', false, 'intermediario'),
('Flexão Escalonada', 'peito', 'composto', 'peso corporal', '3', '8-10 cada lado', '75s', 'Uma mão à frente e outra atrás, troca de lado', false, 'intermediario'),
('Flexão com Déficit (Mãos em Halteres)', 'peito', 'composto', 'halteres', '4', '8-10', '90s', 'Mãos elevadas, peito desce abaixo delas', false, 'intermediario'),
('Flexão na Medicine Ball', 'peito', 'composto', 'medicine ball', '4', '8-10', '90s', 'Mãos na bola, cotovelos rente ao corpo', false, 'intermediario'),
('Flexão na Fita de Suspensão', 'peito', 'composto', 'fita de suspensão', '4', '8-10', '90s', 'Mãos nas alças, corpo em prancha', false, 'intermediario'),
('Flexão com Elástico', 'peito', 'composto', 'elástico', '4', '8-10', '90s', 'Elástico nas costas aumenta a carga no topo', false, 'intermediario'),
('Flexão com Peso nas Costas', 'peito', 'composto', 'anilha', '4', '8-10', '90s', 'Anilha sobre as escápulas, corpo alinhado', false, 'intermediario'),
('Flexão com Pés na Bola Suíça', 'peito', 'composto', 'bola', '4', '8-10', '90s', 'Pés na bola, core trava o balanço', false, 'avancado'),
('Flexão Isométrica (Sustentação no Fundo)', 'peito', 'isolado', 'peso corporal', '3', '20s', '45s', 'Segura a 5cm do chão, cotovelos a 45°', false, 'iniciante'),
('Paralelas Assistidas (Peito)', 'peito', 'composto', 'máquina', '4', '8-10', '90s', 'Contrapeso ajuda, tronco inclinado à frente', false, 'iniciante'),
('Paralelas com Carga (Peito)', 'peito', 'composto', 'peso corporal', '4', '6-8', '2min', 'Cinto com anilha, desce até 90°', false, 'avancado'),
('Crucifixo Reto na Polia (Banco)', 'peito', 'isolado', 'polia', '3', '12-15', '45s', 'Deitado entre as polias baixas, arco aberto', false, 'iniciante'),
('Crucifixo Declinado na Polia (Banco)', 'peito', 'isolado', 'polia', '3', '12-15', '45s', 'Banco declinado, mãos se encontram sobre o peito inferior', false, 'iniciante'),
('Crucifixo no Solo com Halteres', 'peito', 'isolado', 'halteres', '3', '12-15', '45s', 'O chão limita a descida e protege os ombros', false, 'iniciante'),
('Crucifixo Unilateral com Halter', 'peito', 'isolado', 'halteres', '3', '12-15', '45s', 'Um braço por vez, mão livre segura o banco', false, 'intermediario'),
('Crucifixo com Halteres na Bola Suíça', 'peito', 'isolado', 'bola', '3', '12-15', '45s', 'Ombros na bola, cotovelos levemente flexionados', false, 'intermediario'),
('Crucifixo com Elástico', 'peito', 'isolado', 'elástico', '3', '12-15', '45s', 'Elástico preso atrás, fecha os braços à frente', false, 'iniciante'),
('Crucifixo na Fita de Suspensão', 'peito', 'isolado', 'fita de suspensão', '3', '12-15', '45s', 'Abre os braços devagar, corpo em prancha', false, 'intermediario'),
('Crossover Unilateral Baixo', 'peito', 'isolado', 'polia', '3', '12-15', '45s', 'Um braço por vez, de baixo até a linha do queixo', false, 'iniciante'),
('Crossover Unilateral Alto', 'peito', 'isolado', 'polia', '3', '12-15', '45s', 'Um braço por vez, de cima até o quadril oposto', false, 'iniciante'),
('Pullover com Barra', 'peito', 'isolado', 'barra', '3', '12-15', '45s', 'Barra passa atrás da cabeça, cotovelos semiflexionados', false, 'intermediario'),
('Arremesso de Medicine Ball no Peito', 'peito', 'composto', 'medicine ball', '4', '8-10', '60s', 'Arremessa explosivo contra a parede', false, 'iniciante'),

-- Costas
('Barra Fixa Supinada (Chin-Up)', 'costas', 'composto', 'peso corporal', '4', '8-10', '90s', 'Palmas pra você, queixo passa a barra', false, 'intermediario'),
('Barra Fixa com Pegada Neutra', 'costas', 'composto', 'peso corporal', '4', '8-10', '90s', 'Palmas se olhando, cotovelos à frente', false, 'intermediario'),
('Barra Fixa com Pegada Aberta', 'costas', 'composto', 'peso corporal', '4', '6-8', '2min', 'Pegada além dos ombros, peito em direção à barra', false, 'avancado'),
('Barra Fixa com Carga', 'costas', 'composto', 'peso corporal', '4', '5-6', '2min', 'Cinto com anilha, sem balanço', false, 'avancado'),
('Barra Fixa com Elástico', 'costas', 'composto', 'elástico', '4', '8-10', '90s', 'Elástico no joelho ou no pé reduz a carga', false, 'iniciante'),
('Barra Fixa Negativa', 'costas', 'composto', 'peso corporal', '4', '5-6', '90s', 'Sobe com um salto e desce em 5s', false, 'iniciante'),
('Barra Fixa Assistida com os Pés', 'costas', 'composto', 'peso corporal', '4', '8-10', '90s', 'Barra baixa, pés no chão ajudam o mínimo possível', false, 'iniciante'),
('Barra Fixa Arqueiro', 'costas', 'composto', 'peso corporal', '4', '4-6 cada lado', '2min', 'Puxa pra um lado, o outro braço fica estendido', false, 'avancado'),
('Barra Fixa Commando', 'costas', 'composto', 'peso corporal', '4', '6-8', '2min', 'De lado pra barra, cabeça alterna os lados', false, 'avancado'),
('Barra Fixa com Toalha', 'costas', 'composto', 'peso corporal', '4', '5-6', '2min', 'Segura nas toalhas, exige pegada', false, 'avancado'),
('Muscle-Up na Barra', 'costas', 'composto', 'peso corporal', '4', '3-5', '2min', 'Puxada explosiva e transição por cima da barra', false, 'avancado'),
('Sustentação na Barra Fixa (Queixo Acima)', 'costas', 'isolado', 'peso corporal', '3', '15-20s', '60s', 'Segura com o queixo acima da barra', false, 'intermediario'),
('Retração Escapular na Barra Fixa', 'costas', 'isolado', 'peso corporal', '3', '10-12', '45s', 'Braços estendidos, só as escápulas descem', false, 'iniciante'),
('Front Lever Grupado', 'costas', 'isolado', 'peso corporal', '4', '10-15s', '90s', 'Joelhos no peito, costas paralelas ao chão', false, 'avancado'),
('Puxada Unilateral na Polia', 'costas', 'composto', 'polia', '4', '8-10', '90s', 'Um braço por vez, cotovelo desce rente ao corpo', false, 'iniciante'),
('Puxada Unilateral Meio Ajoelhado', 'costas', 'composto', 'polia', '4', '8-10', '90s', 'Um joelho no chão, alonga o dorsal no topo', false, 'iniciante'),
('Puxada Ajoelhado na Polia', 'costas', 'composto', 'polia', '4', '8-10', '90s', 'Ajoelhado de frente pra polia, costelas fechadas', false, 'iniciante'),
('Puxada com Pegada Neutra Aberta', 'costas', 'composto', 'polia', '4', '8-10', '90s', 'Barra longa de pegada neutra, cotovelos pra baixo', false, 'iniciante'),
('Puxada Fechada Pronada', 'costas', 'composto', 'polia', '4', '8-10', '90s', 'Mãos na largura dos ombros, palmas pra frente', false, 'iniciante'),
('Puxada com Cabos Cruzados', 'costas', 'composto', 'polia', '4', '8-10', '90s', 'Cada mão puxa o cabo do lado oposto', false, 'intermediario'),
('Puxada Articulada (High Row)', 'costas', 'composto', 'máquina', '4', '8-10', '90s', 'Puxa de cima pra baixo, um lado independente do outro', false, 'iniciante'),
('Puxada com Elástico', 'costas', 'composto', 'elástico', '4', '8-10', '90s', 'Elástico preso no alto, cotovelos até as costelas', false, 'iniciante'),
('Remada Curvada com Halteres', 'costas', 'composto', 'halteres', '4', '8-10', '90s', 'Tronco a 45°, halteres sobem até o quadril', false, 'iniciante'),
('Remada Curvada no Smith', 'costas', 'composto', 'máquina', '4', '8-10', '90s', 'Barra guiada, puxa até o umbigo', false, 'iniciante'),
('Remada Curvada com Kettlebells', 'costas', 'composto', 'kettlebell', '4', '8-10', '90s', 'Coluna neutra, kettlebells sobem juntos', false, 'iniciante'),
('Remada Unilateral com Kettlebell', 'costas', 'composto', 'kettlebell', '4', '8-10', '90s', 'Mão livre apoiada, cotovelo sobe rente ao corpo', false, 'iniciante'),
('Remada Gorila com Kettlebells', 'costas', 'composto', 'kettlebell', '4', '8-10', '90s', 'Um kettlebell fica no chão enquanto o outro sobe', false, 'intermediario'),
('Remada Renegada', 'costas', 'composto', 'halteres', '3', '8-10 cada lado', '90s', 'Em prancha sobre os halteres, quadril parado', false, 'intermediario'),
('Remada com Peito Apoiado (Halteres)', 'costas', 'composto', 'halteres', '4', '8-10', '90s', 'Peito no banco inclinado, sem roubar com a lombar', false, 'iniciante'),
('Remada com Cotovelos Abertos (Halteres)', 'costas', 'composto', 'halteres', '4', '8-10', '90s', 'Cotovelos abertos a 70°, foco parte alta das costas', false, 'iniciante'),
('Remada Unilateral na Máquina', 'costas', 'composto', 'máquina', '4', '8-10', '90s', 'Um braço por vez, peito colado no apoio', false, 'iniciante'),
('Remada Baixa com Pegada Aberta', 'costas', 'composto', 'polia', '4', '8-10', '90s', 'Barra longa, puxa na linha do peito', false, 'iniciante'),
('Remada Baixa com Pegada Supinada', 'costas', 'composto', 'polia', '4', '8-10', '90s', 'Palmas pra cima, cotovelos rente ao corpo', false, 'iniciante'),
('Remada em Pé na Polia', 'costas', 'composto', 'polia', '4', '8-10', '90s', 'Joelhos semiflexionados, tronco parado', false, 'iniciante'),
('Remada Unilateral em Pé na Polia', 'costas', 'composto', 'polia', '4', '8-10', '90s', 'Base escalonada, sem girar o tronco', false, 'iniciante'),
('Remada com Elástico', 'costas', 'composto', 'elástico', '4', '8-10', '90s', 'Elástico preso à frente, escápulas juntas no final', false, 'iniciante'),
('Remada na Fita de Suspensão', 'costas', 'composto', 'fita de suspensão', '4', '8-10', '90s', 'Corpo reto, quanto mais deitado mais difícil', false, 'iniciante'),
('Remada Unilateral na Fita de Suspensão', 'costas', 'composto', 'fita de suspensão', '4', '8-10', '90s', 'Um braço por vez, quadril de frente', false, 'intermediario'),
('Remada Invertida com Pés Elevados', 'costas', 'composto', 'peso corporal', '4', '8-10', '90s', 'Pés no banco, peito toca a barra', false, 'intermediario'),
('Remada Invertida Supinada', 'costas', 'composto', 'peso corporal', '4', '8-10', '90s', 'Palmas pra você, corpo em prancha', false, 'iniciante'),
('Rack Pull', 'costas', 'composto', 'barra', '4', '5-6', '2min', 'Barra parte da altura do joelho, trava o quadril no topo', false, 'intermediario'),
('Levantamento Terra com Barra Hexagonal', 'costas', 'composto', 'barra', '4', '8-10', '90s', 'Dentro da barra, empurra o chão com as pernas', false, 'iniciante'),
('Levantamento Terra no Smith', 'costas', 'composto', 'máquina', '4', '8-10', '90s', 'Barra guiada rente às pernas', false, 'iniciante'),
('Pulldown Unilateral com Braço Estendido', 'costas', 'isolado', 'polia', '3', '12-15', '45s', 'Braço quase reto, leva a mão até o quadril', false, 'iniciante'),
('Pullover com Elástico', 'costas', 'isolado', 'elástico', '3', '12-15', '45s', 'Elástico preso no alto, braços estendidos', false, 'iniciante'),
('Pullover Deitado na Polia', 'costas', 'isolado', 'polia', '3', '12-15', '45s', 'Deitado de costas pra polia, tensão no alongamento', false, 'iniciante'),
('Encolhimento no Smith', 'costas', 'isolado', 'máquina', '3', '12-15', '45s', 'Barra guiada, sobe os ombros em linha reta', false, 'iniciante'),
('Encolhimento com Barra por Trás', 'costas', 'isolado', 'barra', '3', '12-15', '45s', 'Barra atrás do corpo, peito aberto', false, 'intermediario'),
('Encolhimento na Máquina', 'costas', 'isolado', 'máquina', '3', '12-15', '45s', 'Segura 1s no topo, desce devagar', false, 'iniciante'),
('Encolhimento com Kettlebells', 'costas', 'isolado', 'kettlebell', '3', '12-15', '45s', 'Braços soltos, só os ombros se movem', false, 'iniciante'),
('Encolhimento com Barra Hexagonal', 'costas', 'isolado', 'barra', '3', '12-15', '45s', 'Pegada neutra, permite mais carga', false, 'iniciante'),
('Encolhimento Inclinado com Halteres', 'costas', 'isolado', 'halteres', '3', '12-15', '45s', 'Peito no banco, foco trapézio médio e inferior', false, 'iniciante'),
('Hiperextensão Lombar com Anilha', 'costas', 'isolado', 'anilha', '3', '12-15', '45s', 'Anilha no peito, sobe até alinhar o tronco', false, 'intermediario'),
('Extensão Lombar na Máquina', 'costas', 'isolado', 'máquina', '3', '12-15', '45s', 'Empurra o apoio pra trás sem tranco', false, 'iniciante'),
('Extensão Lombar na Bola Suíça', 'costas', 'isolado', 'bola', '3', '12-15', '45s', 'Quadril na bola, pés firmes na parede', false, 'iniciante'),

-- Ombro
('Desenvolvimento com Halteres em Pé', 'ombro', 'composto', 'halteres', '4', '8-10', '90s', 'Glúteos e core travados, sem arquear a lombar', false, 'intermediario'),
('Desenvolvimento com Pegada Neutra (Halteres)', 'ombro', 'composto', 'halteres', '4', '8-10', '90s', 'Palmas se olhando, cotovelos à frente', false, 'iniciante'),
('Desenvolvimento Alternado com Halteres', 'ombro', 'composto', 'halteres', '4', '8-10', '90s', 'Um braço sobe enquanto o outro espera no ombro', false, 'iniciante'),
('Desenvolvimento Unilateral com Kettlebell', 'ombro', 'composto', 'kettlebell', '4', '8-10', '90s', 'Kettlebell apoiado no antebraço, punho reto', false, 'intermediario'),
('Desenvolvimento com Dois Kettlebells', 'ombro', 'composto', 'kettlebell', '4', '8-10', '90s', 'Parte da posição de rack, costelas fechadas', false, 'intermediario'),
('Desenvolvimento Bottoms-Up com Kettlebell', 'ombro', 'composto', 'kettlebell', '4', '8-10', '90s', 'Kettlebell de cabeça pra baixo, carga leve', false, 'avancado'),
('Z Press', 'ombro', 'composto', 'barra', '4', '8-10', '90s', 'Sentado no chão com as pernas estendidas, sem encosto', false, 'avancado'),
('Desenvolvimento Bradford', 'ombro', 'composto', 'barra', '3', '10-12', '75s', 'Barra passa rente à cabeça, da frente pra trás', false, 'avancado'),
('Desenvolvimento Cubano', 'ombro', 'isolado', 'halteres', '3', '10-12', '60s', 'Remada alta, rotação externa e desenvolvimento', false, 'intermediario'),
('Desenvolvimento na Polia', 'ombro', 'composto', 'polia', '4', '8-10', '90s', 'Polias baixas, tensão constante', false, 'iniciante'),
('Desenvolvimento com Elástico', 'ombro', 'composto', 'elástico', '4', '8-10', '90s', 'Pisa no elástico e empurra acima da cabeça', false, 'iniciante'),
('Desenvolvimento Unilateral na Máquina', 'ombro', 'composto', 'máquina', '4', '8-10', '90s', 'Um braço por vez, tronco colado no encosto', false, 'iniciante'),
('Landmine Press Meio Ajoelhado', 'ombro', 'composto', 'barra', '4', '8-10', '90s', 'Um joelho no chão, empurra com o braço do mesmo lado', false, 'intermediario'),
('Viking Press', 'ombro', 'composto', 'barra', '4', '8-10', '90s', 'Pegada neutra, cabeça passa entre os braços no topo', false, 'intermediario'),
('Push Press com Halteres', 'ombro', 'composto', 'halteres', '4', '8-10', '90s', 'Semiflexão das pernas e empurra de uma vez', false, 'intermediario'),
('Flexão Pike', 'ombro', 'composto', 'peso corporal', '4', '8-10', '90s', 'Quadril alto, cabeça desce entre as mãos', false, 'intermediario'),
('Flexão Pike com Pés Elevados', 'ombro', 'composto', 'peso corporal', '4', '8-10', '90s', 'Pés no banco, tronco quase vertical', false, 'avancado'),
('Flexão em Parada de Mão na Parede', 'ombro', 'composto', 'peso corporal', '4', '4-6', '2min', 'Costas pra parede, cabeça toca o chão de leve', false, 'avancado'),
('Sustentação em Parada de Mão na Parede', 'ombro', 'isolado', 'peso corporal', '3', '20-30s', '60s', 'Empurra o chão, costelas fechadas', false, 'intermediario'),
('Caminhada na Parede (Wall Walk)', 'ombro', 'composto', 'peso corporal', '4', '3-5', '90s', 'Sobe os pés pela parede até ficar vertical', false, 'avancado'),
('Elevação Lateral Sentado', 'ombro', 'isolado', 'halteres', '3', '12-15', '45s', 'Sentado, sem impulso das pernas', false, 'iniciante'),
('Elevação Lateral Inclinada (Apoiado)', 'ombro', 'isolado', 'halteres', '3', '12-15', '45s', 'Segura num apoio e inclina o corpo pro lado', false, 'intermediario'),
('Elevação Lateral no Banco Inclinado', 'ombro', 'isolado', 'halteres', '3', '12-15', '45s', 'Peito no banco, braços sobem pros lados', false, 'iniciante'),
('Elevação Lateral Deitado de Lado', 'ombro', 'isolado', 'halteres', '3', '12-15', '45s', 'Deitado de lado, tensão máxima no começo', false, 'iniciante'),
('Elevação Lateral com Elástico', 'ombro', 'isolado', 'elástico', '3', '12-15', '45s', 'Pisa no elástico, sobe até a linha dos ombros', false, 'iniciante'),
('Elevação Frontal na Polia', 'ombro', 'isolado', 'polia', '3', '12-15', '45s', 'De costas pra polia, cabo entre as pernas', false, 'iniciante'),
('Elevação Frontal com Anilha', 'ombro', 'isolado', 'anilha', '3', '12-15', '45s', 'Segura a anilha pelas bordas, sobe até os olhos', false, 'iniciante'),
('Elevação Frontal com Elástico', 'ombro', 'isolado', 'elástico', '3', '12-15', '45s', 'Pisa no elástico, braços quase estendidos', false, 'iniciante'),
('Elevação Frontal no Banco Inclinado', 'ombro', 'isolado', 'halteres', '3', '12-15', '45s', 'Deitado de costas no banco a 45°, amplitude maior', false, 'intermediario'),
('Volante com Anilha', 'ombro', 'isolado', 'anilha', '3', '10 cada lado', '45s', 'Braços à frente, gira a anilha como um volante', false, 'iniciante'),
('Scaption com Halteres', 'ombro', 'isolado', 'halteres', '3', '12-15', '45s', 'Braços a 30° à frente do corpo, polegares pra cima', false, 'iniciante'),
('Crucifixo Invertido no Banco Inclinado', 'ombro', 'isolado', 'halteres', '3', '12-15', '45s', 'Peito no banco, abre os braços sem encolher os ombros', false, 'iniciante'),
('Crucifixo Invertido Unilateral na Polia', 'ombro', 'isolado', 'polia', '3', '12-15', '45s', 'Um braço por vez, cabo cruza à frente do corpo', false, 'iniciante'),
('Crucifixo Invertido na Fita de Suspensão', 'ombro', 'isolado', 'fita de suspensão', '3', '12-15', '45s', 'Braços abrem em T, corpo reto', false, 'intermediario'),
('Band Pull-Apart', 'ombro', 'isolado', 'elástico', '3', '15-20', '30s', 'Abre o elástico até tocar o peito', false, 'iniciante'),
('Face Pull com Elástico', 'ombro', 'isolado', 'elástico', '3', '12-15', '45s', 'Puxa em direção à testa, cotovelos altos', false, 'iniciante'),
('Face Pull na Fita de Suspensão', 'ombro', 'isolado', 'fita de suspensão', '3', '12-15', '45s', 'Cotovelos altos, mãos ao lado das orelhas', false, 'intermediario'),
('Remada Alta com Halteres', 'ombro', 'composto', 'halteres', '4', '8-10', '90s', 'Halteres sobem rente ao corpo até o peito', false, 'iniciante'),
('Remada Alta na Polia', 'ombro', 'composto', 'polia', '4', '8-10', '90s', 'Barra na polia baixa, cotovelos lideram', false, 'iniciante'),
('Remada Alta com Kettlebell', 'ombro', 'composto', 'kettlebell', '4', '8-10', '90s', 'Segura a alça com as duas mãos', false, 'iniciante'),
('Remada Alta no Smith', 'ombro', 'composto', 'máquina', '4', '8-10', '90s', 'Barra guiada, sobe até a linha do peito', false, 'iniciante'),
('Remada Alta com Elástico', 'ombro', 'composto', 'elástico', '4', '8-10', '90s', 'Pisa no elástico, cotovelos lideram', false, 'iniciante'),
('Remada para Deltoide Posterior com Barra', 'ombro', 'composto', 'barra', '4', '8-10', '90s', 'Pegada aberta, barra sobe até o peito', false, 'intermediario'),
('Rotação Externa Deitado com Halter', 'ombro', 'isolado', 'halteres', '3', '12-15', '45s', 'Deitado de lado, cotovelo colado na cintura', false, 'iniciante'),
('Rotação Externa a 90° na Polia', 'ombro', 'isolado', 'polia', '3', '12-15', '45s', 'Cotovelo na altura do ombro, gira o antebraço pra cima', false, 'intermediario'),
('Rotação Externa em W com Elástico', 'ombro', 'isolado', 'elástico', '3', '12-15', '45s', 'Cotovelos na cintura, abre as mãos pros lados', false, 'iniciante'),
('Rotação Interna na Polia', 'ombro', 'isolado', 'polia', '3', '12-15', '45s', 'Cotovelo colado ao corpo, traz a mão à barriga', false, 'iniciante'),
('Rotação Interna com Elástico', 'ombro', 'isolado', 'elástico', '3', '12-15', '45s', 'Cotovelo a 90°, movimento curto e controlado', false, 'iniciante'),
('Elevação em T no Banco Inclinado', 'ombro', 'isolado', 'halteres', '3', '12-15', '45s', 'Peito no banco, braços abrem em T com polegares pra cima', false, 'iniciante'),
('Elevação em Y na Polia', 'ombro', 'isolado', 'polia', '3', '12-15', '45s', 'Cabos cruzados, braços sobem em Y', false, 'iniciante'),
('Elevação em Y na Fita de Suspensão', 'ombro', 'isolado', 'fita de suspensão', '3', '12-15', '45s', 'Braços sobem em Y, corpo reto', false, 'intermediario'),
('Elevação YTW no Solo', 'ombro', 'isolado', 'peso corporal', '3', '8', '45s', 'Deitado de bruços, desenha Y, T e W com os braços', false, 'iniciante'),
('Halo com Kettlebell', 'ombro', 'isolado', 'kettlebell', '3', '8 cada lado', '45s', 'Kettlebell contorna a cabeça nos dois sentidos', false, 'iniciante'),
('Around the World com Halteres', 'ombro', 'isolado', 'halteres', '3', '12-15', '45s', 'Braços fazem um arco do quadril até acima da cabeça', false, 'intermediario'),
('Encolhimento Acima da Cabeça', 'ombro', 'isolado', 'barra', '3', '12-15', '45s', 'Barra travada acima da cabeça, ombros sobem às orelhas', false, 'intermediario'),
('Flexão Escapular', 'ombro', 'isolado', 'peso corporal', '3', '12-15', '45s', 'Braços estendidos, só as escápulas abrem e fecham', false, 'iniciante'),
('Deslizamento na Parede (Wall Slide)', 'ombro', 'isolado', 'peso corporal', '3', '12-15', '45s', 'Costas e antebraços na parede, sobe e desce', false, 'iniciante'),

-- Bíceps
('Rosca Direta com Halteres', 'biceps', 'isolado', 'halteres', '3', '12-15', '45s', 'Os dois braços juntos, cotovelos parados', false, 'iniciante'),
('Rosca com Pegada Aberta (Barra)', 'biceps', 'isolado', 'barra', '3', '12-15', '45s', 'Pegada além dos ombros, foco cabeça curta', false, 'iniciante'),
('Rosca com Pegada Fechada (Barra)', 'biceps', 'isolado', 'barra', '3', '12-15', '45s', 'Mãos próximas, foco cabeça longa', false, 'iniciante'),
('Rosca Drag com Barra', 'biceps', 'isolado', 'barra', '3', '12-15', '45s', 'Barra sobe arrastando no tronco, cotovelos vão pra trás', false, 'intermediario'),
('Rosca Drag com Halteres', 'biceps', 'isolado', 'halteres', '3', '12-15', '45s', 'Halteres sobem rente ao corpo, cotovelos vão pra trás', false, 'intermediario'),
('Rosca Scott Unilateral com Halter', 'biceps', 'isolado', 'halteres', '3', '12-15', '45s', 'Um braço por vez, não estende por completo', false, 'iniciante'),
('Rosca Scott Martelo', 'biceps', 'isolado', 'halteres', '3', '12-15', '45s', 'Pegada neutra no banco Scott', false, 'iniciante'),
('Rosca Scott Inversa', 'biceps', 'isolado', 'barra', '3', '12-15', '45s', 'Pegada pronada no banco Scott, carga leve', false, 'intermediario'),
('Rosca Scott na Polia', 'biceps', 'isolado', 'polia', '3', '12-15', '45s', 'Banco Scott de frente pra polia baixa', false, 'iniciante'),
('Rosca Spider com Barra W', 'biceps', 'isolado', 'barra', '3', '12-15', '45s', 'Peito no banco inclinado, braços pendurados', false, 'iniciante'),
('Rosca Martelo Inclinada', 'biceps', 'isolado', 'halteres', '3', '12-15', '45s', 'Banco a 45°, pegada neutra', false, 'iniciante'),
('Rosca Unilateral na Polia Baixa', 'biceps', 'isolado', 'polia', '3', '12-15', '45s', 'Um braço por vez, cotovelo colado ao corpo', false, 'iniciante'),
('Rosca Bayesian na Polia', 'biceps', 'isolado', 'polia', '3', '12-15', '45s', 'De costas pra polia, braço começa atrás do tronco', false, 'intermediario'),
('Rosca Deitado na Polia', 'biceps', 'isolado', 'polia', '3', '12-15', '45s', 'Deitado no chão, elimina o balanço', false, 'iniciante'),
('Rosca Concentrada na Polia', 'biceps', 'isolado', 'polia', '3', '12-15', '45s', 'Cotovelo apoiado na coxa, tensão constante', false, 'iniciante'),
('Rosca Direta na Máquina', 'biceps', 'isolado', 'máquina', '3', '12-15', '45s', 'Braços apoiados, sobe sem tirar os cotovelos', false, 'iniciante'),
('Rosca com Kettlebell', 'biceps', 'isolado', 'kettlebell', '3', '12-15', '45s', 'Segura a alça com as duas mãos', false, 'iniciante'),
('Rosca com Anilha', 'biceps', 'isolado', 'anilha', '3', '12-15', '45s', 'Segura a anilha pelas bordas, punhos firmes', false, 'iniciante'),
('Rosca Waiter', 'biceps', 'isolado', 'halteres', '3', '12-15', '45s', 'Segura um halter pela cabeça, palmas pra cima', false, 'iniciante'),
('Rosca com Elástico', 'biceps', 'isolado', 'elástico', '3', '12-15', '45s', 'Pisa no elástico, cotovelos parados', false, 'iniciante'),
('Rosca Martelo com Elástico', 'biceps', 'isolado', 'elástico', '3', '12-15', '45s', 'Pisa no elástico, pegada neutra', false, 'iniciante'),
('Rosca na Fita de Suspensão', 'biceps', 'isolado', 'fita de suspensão', '3', '12-15', '45s', 'Cotovelos altos, traz as mãos à testa', false, 'intermediario'),
('Rosca Apoiado na Parede', 'biceps', 'isolado', 'barra', '3', '12-15', '45s', 'Costas e cotovelos na parede, sem roubar', false, 'iniciante'),
('Rosca Isométrica a 90°', 'biceps', 'isolado', 'halteres', '3', '30s', '45s', 'Segura os halteres com os cotovelos a 90°', false, 'iniciante'),
('Rosca Alternada com Isometria', 'biceps', 'isolado', 'halteres', '3', '8-10 cada lado', '60s', 'Um braço segura a 90° enquanto o outro trabalha', false, 'intermediario'),
('Rosca Inclinada Alternada com Supinação', 'biceps', 'isolado', 'halteres', '3', '10-12', '60s', 'Começa em pegada neutra e gira o punho na subida', false, 'intermediario'),

-- Tríceps
('Tríceps Pulley Barra V', 'triceps', 'isolado', 'polia', '3', '12-15', '45s', 'Punhos neutros, cotovelos colados', false, 'iniciante'),
('Tríceps Pulley Unilateral Invertido', 'triceps', 'isolado', 'polia', '3', '12-15', '45s', 'Palma pra cima, um braço por vez', false, 'iniciante'),
('Tríceps Pulley com Elástico', 'triceps', 'isolado', 'elástico', '3', '12-15', '45s', 'Elástico preso no alto, estende até travar', false, 'iniciante'),
('Tríceps Cruzado na Polia', 'triceps', 'isolado', 'polia', '3', '12-15', '45s', 'Cada mão segura o cabo do lado oposto', false, 'iniciante'),
('Tríceps Francês com Barra W', 'triceps', 'isolado', 'barra', '3', '12-15', '45s', 'Barra desce atrás da cabeça, cotovelos pra frente', false, 'intermediario'),
('Tríceps Francês Unilateral com Halter', 'triceps', 'isolado', 'halteres', '3', '12-15', '45s', 'Um braço por vez, mão livre apoia o cotovelo', false, 'iniciante'),
('Tríceps Francês Unilateral na Polia', 'triceps', 'isolado', 'polia', '3', '12-15', '45s', 'De costas pra polia baixa, um braço por vez', false, 'iniciante'),
('Tríceps Francês com Kettlebell', 'triceps', 'isolado', 'kettlebell', '3', '12-15', '45s', 'Segura o kettlebell pelas alças laterais', false, 'iniciante'),
('Tríceps Francês com Anilha', 'triceps', 'isolado', 'anilha', '3', '12-15', '45s', 'Anilha desce atrás da cabeça, cotovelos fechados', false, 'iniciante'),
('Tríceps Francês com Elástico', 'triceps', 'isolado', 'elástico', '3', '12-15', '45s', 'Pisa no elástico e estende acima da cabeça', false, 'iniciante'),
('Tríceps Testa na Polia', 'triceps', 'isolado', 'polia', '3', '12-15', '45s', 'Deitado de costas pra polia baixa', false, 'iniciante'),
('Tríceps Testa com Barra Reta', 'triceps', 'isolado', 'barra', '3', '12-15', '45s', 'Barra desce até a testa, cotovelos apontando pro teto', false, 'intermediario'),
('Tríceps Testa Inclinado', 'triceps', 'isolado', 'barra', '3', '12-15', '45s', 'Banco a 30°, mais alongamento da cabeça longa', false, 'intermediario'),
('Tríceps Testa Cruzado com Halter', 'triceps', 'isolado', 'halteres', '3', '12-15', '45s', 'Halter desce em direção ao ombro oposto', false, 'iniciante'),
('Tríceps Testa com Pullover', 'triceps', 'isolado', 'barra', '3', '12-15', '45s', 'Barra vai atrás da cabeça antes de estender', false, 'intermediario'),
('Tríceps Rolling com Halteres', 'triceps', 'isolado', 'halteres', '3', '12-15', '45s', 'Cotovelos rolam pra trás na descida', false, 'intermediario'),
('Tate Press', 'triceps', 'isolado', 'halteres', '3', '12-15', '45s', 'Cotovelos abertos, halteres descem ao peito', false, 'intermediario'),
('JM Press', 'triceps', 'composto', 'barra', '4', '6-8', '2min', 'Mistura de supino fechado com tríceps testa', false, 'avancado'),
('Supino Fechado com Halteres', 'triceps', 'composto', 'halteres', '4', '8-10', '90s', 'Halteres juntos, cotovelos rente ao corpo', false, 'iniciante'),
('Tríceps na Máquina', 'triceps', 'isolado', 'máquina', '3', '12-15', '45s', 'Cotovelos apoiados, estende até travar', false, 'iniciante'),
('Tríceps Coice com Elástico', 'triceps', 'isolado', 'elástico', '3', '12-15', '45s', 'Tronco inclinado, estende o braço pra trás', false, 'iniciante'),
('Flexão Fechada', 'triceps', 'composto', 'peso corporal', '4', '8-10', '90s', 'Mãos na largura dos ombros, cotovelos rente ao corpo', false, 'intermediario'),
('Flexão Fechada com Joelhos Apoiados', 'triceps', 'composto', 'peso corporal', '3', '10-12', '60s', 'Joelhos no chão, cotovelos rente ao corpo', false, 'iniciante'),
('Flexão Esfinge', 'triceps', 'composto', 'peso corporal', '3', '8-10', '75s', 'Parte dos antebraços no chão e estende os cotovelos', false, 'avancado'),
('Extensão de Tríceps no Banco (Peso Corporal)', 'triceps', 'isolado', 'peso corporal', '3', '10-12', '60s', 'Mãos no banco, cabeça desce abaixo das mãos', false, 'intermediario'),
('Extensão de Tríceps na Fita de Suspensão', 'triceps', 'isolado', 'fita de suspensão', '3', '10-12', '60s', 'Cotovelos apontam pra frente, corpo em prancha', false, 'intermediario'),
('Mergulho no Banco com Pés Elevados', 'triceps', 'composto', 'peso corporal', '4', '8-10', '90s', 'Pés em outro banco, desce até 90°', false, 'intermediario'),
('Mergulho no Banco com Carga', 'triceps', 'composto', 'anilha', '4', '8-10', '90s', 'Anilha sobre as coxas, ombros longe das orelhas', false, 'intermediario'),
('Paralelas Assistidas (Tríceps)', 'triceps', 'composto', 'máquina', '4', '8-10', '90s', 'Contrapeso ajuda, tronco ereto', false, 'iniciante'),
('Paralelas com Carga (Tríceps)', 'triceps', 'composto', 'peso corporal', '4', '6-8', '2min', 'Cinto com anilha, tronco ereto', false, 'avancado'),

-- Antebraço
('Rosca de Punho com Barra', 'antebraco', 'isolado', 'barra', '3', '15-20', '45s', 'Antebraços apoiados, só o punho se move', false, 'iniciante'),
('Rosca de Punho Inversa com Barra', 'antebraco', 'isolado', 'barra', '3', '15-20', '45s', 'Palmas pra baixo, carga leve', false, 'iniciante'),
('Rosca de Punho com Halteres', 'antebraco', 'isolado', 'halteres', '3', '15-20', '45s', 'Antebraços nas coxas, palmas pra cima', false, 'iniciante'),
('Rosca de Punho Inversa com Halteres', 'antebraco', 'isolado', 'halteres', '3', '15-20', '45s', 'Antebraços nas coxas, palmas pra baixo', false, 'iniciante'),
('Rosca de Punho por Trás', 'antebraco', 'isolado', 'barra', '3', '15-20', '45s', 'Em pé, barra atrás do corpo', false, 'iniciante'),
('Rosca de Punho na Polia', 'antebraco', 'isolado', 'polia', '3', '15-20', '45s', 'Sentado de frente pra polia baixa', false, 'iniciante'),
('Rosca de Dedos com Barra', 'antebraco', 'isolado', 'barra', '3', '15-20', '45s', 'Barra rola até a ponta dos dedos e volta', false, 'iniciante'),
('Rosca Inversa com Halteres', 'antebraco', 'isolado', 'halteres', '3', '12-15', '45s', 'Palmas pra baixo, punhos retos', false, 'iniciante'),
('Rosca Inversa com Barra W', 'antebraco', 'isolado', 'barra', '3', '12-15', '45s', 'Pegada pronada na barra W, cotovelos parados', false, 'iniciante'),
('Rosca Inversa na Polia', 'antebraco', 'isolado', 'polia', '3', '12-15', '45s', 'Pegada pronada na barra reta, tensão constante', false, 'iniciante'),
('Rolo de Punho', 'antebraco', 'isolado', 'anilha', '3', '3-4', '60s', 'Enrola a corda até a anilha subir, depois desenrola', false, 'iniciante'),
('Pinça com Anilhas', 'antebraco', 'isolado', 'anilha', '3', '20-30s', '60s', 'Segura as anilhas só com a ponta dos dedos', false, 'iniciante'),
('Pronação e Supinação com Halter', 'antebraco', 'isolado', 'halteres', '3', '12 cada lado', '45s', 'Cotovelo a 90°, gira o antebraço devagar', false, 'iniciante'),
('Desvio Radial com Halter', 'antebraco', 'isolado', 'halteres', '3', '15-20', '45s', 'Braço ao lado do corpo, punho sobe pro polegar', false, 'iniciante'),
('Desvio Ulnar com Halter', 'antebraco', 'isolado', 'halteres', '3', '15-20', '45s', 'Braço ao lado do corpo, punho sobe pro dedo mínimo', false, 'iniciante'),
('Extensão de Dedos com Elástico', 'antebraco', 'isolado', 'elástico', '3', '20', '30s', 'Abre os dedos contra o elástico', false, 'iniciante'),
('Sustentação na Barra Fixa (Dead Hang)', 'antebraco', 'isolado', 'peso corporal', '3', '30s', '60s', 'Pendurado com os braços estendidos', false, 'iniciante'),
('Sustentação na Barra com Toalha', 'antebraco', 'isolado', 'peso corporal', '3', '20s', '60s', 'Pendurado nas toalhas, pegada esmagando', false, 'intermediario'),
('Sustentação de Barra', 'antebraco', 'isolado', 'barra', '3', '30s', '60s', 'Segura a barra carregada em pé, ombros encaixados', false, 'intermediario'),

-- Quadríceps
('Agachamento sem Peso', 'quadriceps', 'composto', 'peso corporal', '3', '15-20', '60s', 'Braços à frente, calcanhares no chão', false, 'iniciante'),
('Agachamento Goblet com Halter', 'quadriceps', 'composto', 'halteres', '4', '8-10', '90s', 'Halter junto ao peito, cotovelos entre os joelhos', false, 'iniciante'),
('Agachamento com Halteres', 'quadriceps', 'composto', 'halteres', '4', '8-10', '90s', 'Halteres ao lado do corpo, tronco ereto', false, 'iniciante'),
('Agachamento no Banco (Box Squat)', 'quadriceps', 'composto', 'barra', '4', '8-10', '90s', 'Senta no banco sem relaxar e sobe', false, 'intermediario'),
('Agachamento Zercher', 'quadriceps', 'composto', 'barra', '4', '8-10', '90s', 'Barra na dobra dos cotovelos', false, 'avancado'),
('Agachamento Overhead', 'quadriceps', 'composto', 'barra', '4', '5-6', '2min', 'Barra travada acima da cabeça, pegada aberta', false, 'avancado'),
('Agachamento Frontal com Halteres', 'quadriceps', 'composto', 'halteres', '4', '8-10', '90s', 'Halteres apoiados nos ombros', false, 'intermediario'),
('Agachamento Frontal com Kettlebells', 'quadriceps', 'composto', 'kettlebell', '4', '8-10', '90s', 'Kettlebells na posição de rack, cotovelos baixos', false, 'intermediario'),
('Agachamento Frontal no Smith', 'quadriceps', 'composto', 'máquina', '4', '8-10', '90s', 'Barra guiada nos ombros, pés um pouco à frente', false, 'iniciante'),
('Agachamento Hack com Barra', 'quadriceps', 'composto', 'barra', '4', '8-10', '90s', 'Barra atrás das pernas, sobe rente aos glúteos', false, 'avancado'),
('Agachamento Hack Invertido', 'quadriceps', 'composto', 'máquina', '4', '8-10', '90s', 'De frente pro encosto, quadril vai pra trás', false, 'intermediario'),
('Agachamento na Máquina V-Squat', 'quadriceps', 'composto', 'máquina', '4', '8-10', '90s', 'Ombros no apoio, desce em arco', false, 'iniciante'),
('Agachamento no Cinto (Belt Squat)', 'quadriceps', 'composto', 'máquina', '4', '8-10', '90s', 'Carga presa no quadril, coluna livre', false, 'iniciante'),
('Agachamento Landmine', 'quadriceps', 'composto', 'barra', '4', '8-10', '90s', 'Segura a ponta da barra no peito', false, 'iniciante'),
('Agachamento Sumô com Barra', 'quadriceps', 'composto', 'barra', '4', '8-10', '90s', 'Base larga, joelhos acompanham os pés', false, 'intermediario'),
('Agachamento Sumô no Smith', 'quadriceps', 'composto', 'máquina', '4', '8-10', '90s', 'Barra guiada, base larga', false, 'iniciante'),
('Agachamento com Elástico', 'quadriceps', 'composto', 'elástico', '3', '12-15', '60s', 'Pisa no elástico e leva as alças aos ombros', false, 'iniciante'),
('Agachamento Ciclista', 'quadriceps', 'composto', 'halteres', '4', '8-10', '90s', 'Calcanhares elevados e pés juntos', false, 'intermediario'),
('Agachamento Cossaco', 'quadriceps', 'composto', 'peso corporal', '3', '8-10 cada lado', '75s', 'Desce sobre uma perna, a outra fica estendida', false, 'intermediario'),
('Agachamento Espanhol com Elástico', 'quadriceps', 'isolado', 'elástico', '3', '12-15', '45s', 'Elástico atrás dos joelhos, canelas verticais', false, 'iniciante'),
('Agachamento Hindu', 'quadriceps', 'composto', 'peso corporal', '3', '15-20', '60s', 'Calcanhares sobem na descida, ritmo contínuo', false, 'iniciante'),
('Agachamento com Salto', 'quadriceps', 'composto', 'peso corporal', '4', '8-10', '75s', 'Salta o mais alto que der, amortece a queda', false, 'intermediario'),
('Agachamento Pistol', 'quadriceps', 'composto', 'peso corporal', '4', '4-6 cada perna', '2min', 'Uma perna só, a outra estendida à frente', false, 'avancado'),
('Agachamento Skater', 'quadriceps', 'composto', 'peso corporal', '3', '6-8 cada perna', '90s', 'Joelho de trás desce até quase tocar o chão', false, 'avancado'),
('Agachamento Camarão (Shrimp Squat)', 'quadriceps', 'composto', 'peso corporal', '3', '5-6 cada perna', '90s', 'Segura o pé de trás com a mão', false, 'avancado'),
('Agachamento na Fita de Suspensão', 'quadriceps', 'composto', 'fita de suspensão', '3', '12-15', '60s', 'Segura nas alças pra equilibrar e desce fundo', false, 'iniciante'),
('Agachamento na Parede com Bola Suíça', 'quadriceps', 'composto', 'bola', '3', '12-15', '60s', 'Bola entre a lombar e a parede', false, 'iniciante'),
('Agachamento Isométrico Unilateral na Parede', 'quadriceps', 'isolado', 'peso corporal', '3', '20s cada perna', '45s', 'Uma perna estendida à frente', false, 'intermediario'),
('Sissy Squat na Máquina', 'quadriceps', 'isolado', 'máquina', '3', '12-15', '45s', 'Canelas presas, senta pra trás', false, 'intermediario'),
('Leg Press Horizontal', 'quadriceps', 'composto', 'máquina', '4', '8-10', '90s', 'Sentado, empurra a plataforma à frente', false, 'iniciante'),
('Leg Press Vertical', 'quadriceps', 'composto', 'máquina', '4', '8-10', '90s', 'Deitado, empurra a carga pra cima', false, 'intermediario'),
('Afundo Reverso com Halteres', 'quadriceps', 'composto', 'halteres', '4', '8-10', '90s', 'Passo pra trás, tronco ereto', false, 'iniciante'),
('Afundo Reverso com Barra', 'quadriceps', 'composto', 'barra', '4', '8-10', '90s', 'Barra nas costas, passo pra trás', false, 'intermediario'),
('Afundo Reverso no Smith', 'quadriceps', 'composto', 'máquina', '4', '8-10', '90s', 'Barra guiada, passo pra trás', false, 'iniciante'),
('Afundo Reverso com Déficit', 'quadriceps', 'composto', 'halteres', '4', '8-10', '90s', 'Pé da frente num step, amplitude maior', false, 'intermediario'),
('Afundo Reverso com Deslizamento', 'quadriceps', 'composto', 'peso corporal', '3', '10-12 cada perna', '60s', 'Pé de trás desliza num pano ou disco', false, 'iniciante'),
('Afundo Frontal Alternado', 'quadriceps', 'composto', 'peso corporal', '3', '10-12 cada perna', '60s', 'Passo à frente e volta, alternando as pernas', false, 'iniciante'),
('Afundo no Smith', 'quadriceps', 'composto', 'máquina', '4', '8-10', '90s', 'Barra guiada, base fixa', false, 'iniciante'),
('Afundo com Salto', 'quadriceps', 'composto', 'peso corporal', '3', '8-10 cada perna', '75s', 'Troca as pernas no ar', false, 'intermediario'),
('Afundo Búlgaro com Barra', 'quadriceps', 'composto', 'barra', '4', '8-10', '90s', 'Barra nas costas, pé de trás no banco', false, 'avancado'),
('Step-Up Lateral', 'quadriceps', 'composto', 'halteres', '4', '8-10', '90s', 'Sobe de lado no banco', false, 'iniciante'),
('Step-Up com Barra', 'quadriceps', 'composto', 'barra', '4', '8-10', '90s', 'Barra nas costas, sobe sem impulso da perna de baixo', false, 'intermediario'),
('Step-Down', 'quadriceps', 'composto', 'peso corporal', '3', '8-10 cada perna', '60s', 'Desce do step em 3s, calcanhar toca o chão de leve', false, 'iniciante'),
('Poliquin Step-Up', 'quadriceps', 'isolado', 'peso corporal', '3', '12-15 cada perna', '45s', 'Calcanhar elevado, degrau baixo', false, 'iniciante'),
('Salto no Caixote', 'quadriceps', 'composto', 'peso corporal', '4', '5-6', '90s', 'Aterrissa macio e desce andando', false, 'intermediario'),
('Salto em Distância', 'quadriceps', 'composto', 'peso corporal', '4', '5-6', '90s', 'Balança os braços e salta pra frente', false, 'intermediario'),
('Thruster com Halteres', 'quadriceps', 'composto', 'halteres', '4', '10-12', '90s', 'Agachamento frontal emendado com desenvolvimento', false, 'intermediario'),
('Thruster com Barra', 'quadriceps', 'composto', 'barra', '4', '8-10', '2min', 'Sobe do agachamento empurrando a barra', false, 'avancado'),
('Empurrada de Trenó', 'quadriceps', 'composto', 'trenó', '4', '20m', '90s', 'Tronco inclinado, passos curtos e fortes', false, 'intermediario'),
('Arrasto de Trenó de Costas', 'quadriceps', 'composto', 'trenó', '4', '20m', '90s', 'Anda de costas puxando o trenó', false, 'iniciante'),
('Extensão de Joelho na Polia', 'quadriceps', 'isolado', 'polia', '3', '12-15', '45s', 'Caneleira da polia no tornozelo, sentado', false, 'iniciante'),
('Extensora com Elástico', 'quadriceps', 'isolado', 'elástico', '3', '12-15', '45s', 'Elástico no tornozelo, estende e segura 1s', false, 'iniciante'),
('Extensão Terminal de Joelho com Elástico', 'quadriceps', 'isolado', 'elástico', '3', '15-20 cada perna', '30s', 'Elástico atrás do joelho, estende até travar', false, 'iniciante'),
('Nordic Reverso', 'quadriceps', 'isolado', 'peso corporal', '3', '8-10', '60s', 'Ajoelhado, inclina pra trás com o quadril estendido', false, 'intermediario'),
('Elevação de Perna Estendida com Caneleira', 'quadriceps', 'isolado', 'caneleira', '3', '12-15 cada perna', '45s', 'Deitado, joelho travado, sobe até a outra coxa', false, 'iniciante'),
('Adução de Quadril na Polia', 'quadriceps', 'isolado', 'polia', '3', '12-15 cada perna', '45s', 'Caneleira da polia no tornozelo, cruza à frente', false, 'iniciante'),
('Adução de Quadril Deitado de Lado', 'quadriceps', 'isolado', 'peso corporal', '3', '15-20 cada perna', '30s', 'Perna de baixo sobe, a de cima fica à frente', false, 'iniciante'),
('Aperto de Bola entre os Joelhos', 'quadriceps', 'isolado', 'bola', '3', '10', '30s', 'Aperta a bola e segura 5s', false, 'iniciante'),

-- Posterior de coxa
('Romeno com Halteres', 'posterior_coxa', 'composto', 'halteres', '4', '8-10', '90s', 'Halteres descem rente às pernas, quadril vai pra trás', false, 'iniciante'),
('Romeno no Smith', 'posterior_coxa', 'composto', 'máquina', '4', '8-10', '90s', 'Barra guiada, quadril vai pra trás', false, 'iniciante'),
('Romeno com Barra Hexagonal', 'posterior_coxa', 'composto', 'barra', '4', '8-10', '90s', 'Pegada neutra, joelhos pouco flexionados', false, 'intermediario'),
('Romeno na Polia', 'posterior_coxa', 'composto', 'polia', '4', '8-10', '90s', 'De frente pra polia baixa, tensão no alongamento', false, 'iniciante'),
('Romeno com Elástico', 'posterior_coxa', 'composto', 'elástico', '3', '12-15', '60s', 'Pisa no elástico, quadril vai pra trás', false, 'iniciante'),
('Romeno Landmine', 'posterior_coxa', 'composto', 'barra', '4', '8-10', '90s', 'Segura a ponta da barra com as duas mãos', false, 'iniciante'),
('Romeno com Base Escalonada (B-Stance)', 'posterior_coxa', 'composto', 'halteres', '4', '8-10 cada perna', '90s', 'Um pé atrás só de apoio, carga na perna da frente', false, 'intermediario'),
('Romeno com Pegada Aberta', 'posterior_coxa', 'composto', 'barra', '4', '8-10', '90s', 'Pegada bem aberta, mais trabalho das costas', false, 'avancado'),
('Stiff com Déficit', 'posterior_coxa', 'composto', 'barra', '4', '8-10', '90s', 'Em cima de uma anilha, alongamento maior', false, 'avancado'),
('Good Morning com Elástico', 'posterior_coxa', 'composto', 'elástico', '3', '12-15', '60s', 'Elástico na nuca e sob os pés', false, 'iniciante'),
('Good Morning no Smith', 'posterior_coxa', 'composto', 'máquina', '4', '8-10', '90s', 'Barra guiada, joelhos pouco flexionados', false, 'intermediario'),
('Good Morning Sentado', 'posterior_coxa', 'composto', 'barra', '4', '8-10', '90s', 'Sentado no banco, tronco desce entre as pernas', false, 'avancado'),
('Levantamento Terra com Kettlebell', 'posterior_coxa', 'composto', 'kettlebell', '4', '8-10', '90s', 'Kettlebell entre os pés, coluna neutra', false, 'iniciante'),
('Levantamento Terra Sumô com Kettlebell', 'posterior_coxa', 'composto', 'kettlebell', '4', '8-10', '90s', 'Base larga, kettlebell sobe rente ao corpo', false, 'iniciante'),
('Kettlebell Swing', 'posterior_coxa', 'composto', 'kettlebell', '4', '15', '60s', 'Quadril explode, braços só conduzem', false, 'intermediario'),
('Kettlebell Swing Unilateral', 'posterior_coxa', 'composto', 'kettlebell', '4', '10 cada lado', '60s', 'Uma mão, ombros de frente', false, 'intermediario'),
('Glute-Ham Raise', 'posterior_coxa', 'composto', 'máquina', '4', '6-8', '2min', 'Joelhos no apoio, sobe flexionando os joelhos', false, 'avancado'),
('Flexora Nórdica com Elástico', 'posterior_coxa', 'composto', 'elástico', '3', '6-8', '90s', 'Elástico no peito alivia a descida', false, 'intermediario'),
('Flexora Deitado na Polia', 'posterior_coxa', 'isolado', 'polia', '3', '12-15', '45s', 'De bruços, caneleira da polia no tornozelo', false, 'iniciante'),
('Flexora em Pé na Polia', 'posterior_coxa', 'isolado', 'polia', '3', '12-15 cada perna', '45s', 'Apoiado, calcanhar sobe ao glúteo', false, 'iniciante'),
('Flexora com Elástico', 'posterior_coxa', 'isolado', 'elástico', '3', '12-15', '45s', 'De bruços, elástico preso no tornozelo', false, 'iniciante'),
('Flexora com Deslizamento', 'posterior_coxa', 'isolado', 'peso corporal', '3', '10-12', '60s', 'Calcanhares deslizam, quadril alto', false, 'intermediario'),
('Flexora na Fita de Suspensão', 'posterior_coxa', 'isolado', 'fita de suspensão', '3', '10-12', '60s', 'Calcanhares nas alças, quadril alto', false, 'intermediario'),
('Flexora Unilateral na Bola Suíça', 'posterior_coxa', 'isolado', 'bola', '3', '8-10 cada perna', '60s', 'Uma perna na bola, a outra no ar', false, 'avancado'),
('Ponte de Posterior', 'posterior_coxa', 'isolado', 'peso corporal', '3', '12-15', '45s', 'Calcanhares longe do quadril, sobe o quadril', false, 'iniciante'),
('Ponte de Posterior Unilateral no Banco', 'posterior_coxa', 'isolado', 'peso corporal', '3', '10-12 cada perna', '45s', 'Um calcanhar no banco, a outra perna no ar', false, 'intermediario'),
('Caminhada de Calcanhares na Ponte', 'posterior_coxa', 'isolado', 'peso corporal', '3', '6-8', '60s', 'Da ponte, afasta os calcanhares passo a passo', false, 'intermediario'),

-- Glúteos
('Elevação Pélvica com Halter', 'gluteos', 'composto', 'halteres', '4', '8-10', '90s', 'Halter sobre o quadril, costas no banco', false, 'iniciante'),
('Elevação Pélvica com Elástico', 'gluteos', 'composto', 'elástico', '3', '12-15', '60s', 'Elástico sobre o quadril, pausa no topo', false, 'iniciante'),
('Elevação Pélvica Unilateral com Halter', 'gluteos', 'composto', 'halteres', '4', '8-10 cada perna', '90s', 'Uma perna no ar, quadril nivelado', false, 'intermediario'),
('Elevação Pélvica com Base Escalonada (B-Stance)', 'gluteos', 'composto', 'barra', '4', '8-10 cada perna', '90s', 'Um pé à frente só de apoio', false, 'intermediario'),
('Elevação Pélvica com Abdução', 'gluteos', 'composto', 'elástico', '3', '12-15', '60s', 'Mini band nos joelhos, abre no topo', false, 'iniciante'),
('Elevação Pélvica com Pés Elevados', 'gluteos', 'composto', 'peso corporal', '3', '12-15', '60s', 'Costas no chão, pés no banco', false, 'iniciante'),
('Elevação Pélvica na Bola Suíça', 'gluteos', 'composto', 'bola', '3', '12-15', '60s', 'Ombros na bola, quadril sobe e desce', false, 'iniciante'),
('Kas Glute Bridge', 'gluteos', 'composto', 'barra', '4', '10-12', '75s', 'Amplitude curta, só o terço final', false, 'intermediario'),
('Ponte de Glúteo com Barra', 'gluteos', 'composto', 'barra', '4', '8-10', '90s', 'Costas no chão, barra sobre o quadril', false, 'iniciante'),
('Ponte de Glúteo com Mini Band', 'gluteos', 'isolado', 'elástico', '3', '12-15', '45s', 'Mini band nos joelhos, joelhos pra fora', false, 'iniciante'),
('Ponte de Glúteo com Marcha', 'gluteos', 'isolado', 'peso corporal', '3', '10 cada perna', '45s', 'Quadril alto, alterna as pernas sem cair', false, 'iniciante'),
('Ponte de Glúteo Isométrica', 'gluteos', 'isolado', 'peso corporal', '3', '30s', '30s', 'Segura no topo contraindo o glúteo', false, 'iniciante'),
('Coice no Smith', 'gluteos', 'isolado', 'máquina', '3', '12-15 cada perna', '45s', 'Em 4 apoios, a sola do pé empurra a barra', false, 'intermediario'),
('Coice com Elástico', 'gluteos', 'isolado', 'elástico', '3', '12-15 cada perna', '45s', 'Elástico nos tornozelos, perna vai pra trás', false, 'iniciante'),
('Coice em Pé com Caneleira', 'gluteos', 'isolado', 'caneleira', '3', '15-20 cada perna', '45s', 'Apoiado, perna estendida vai pra trás', false, 'iniciante'),
('Coice com Halter em 4 Apoios', 'gluteos', 'isolado', 'halteres', '3', '12-15 cada perna', '45s', 'Halter preso atrás do joelho', false, 'iniciante'),
('Hidrante', 'gluteos', 'isolado', 'peso corporal', '3', '15-20 cada perna', '30s', 'Em 4 apoios, joelho abre pro lado', false, 'iniciante'),
('Arco-Íris em 4 Apoios', 'gluteos', 'isolado', 'peso corporal', '3', '12 cada perna', '30s', 'Perna estendida desenha um arco de um lado ao outro', false, 'iniciante'),
('Ostra com Mini Band', 'gluteos', 'isolado', 'elástico', '3', '15-20 cada lado', '30s', 'Deitado de lado, abre o joelho sem rodar o quadril', false, 'iniciante'),
('Abdução em Pé com Elástico', 'gluteos', 'isolado', 'elástico', '3', '15 cada perna', '30s', 'Elástico nos tornozelos, perna abre pro lado', false, 'iniciante'),
('Abdução Sentado com Mini Band', 'gluteos', 'isolado', 'elástico', '3', '20', '30s', 'Sentado, abre os joelhos contra o elástico', false, 'iniciante'),
('Abdução em Pé na Máquina', 'gluteos', 'isolado', 'máquina', '3', '12-15 cada perna', '45s', 'Em pé, perna abre contra o apoio', false, 'iniciante'),
('Elevação de Quadril Deitado de Lado', 'gluteos', 'isolado', 'peso corporal', '3', '10-12 cada lado', '45s', 'Apoiado no antebraço, quadril sobe e a perna abre', false, 'intermediario'),
('Caminhada Monstro com Mini Band', 'gluteos', 'isolado', 'elástico', '3', '12 passos cada lado', '45s', 'Passos largos na diagonal, joelhos pra fora', false, 'iniciante'),
('Extensão de Quadril no Banco Romano', 'gluteos', 'composto', 'peso corporal', '3', '12-15', '60s', 'Costas arredondadas, sobe apertando o glúteo', false, 'iniciante'),
('Hiperextensão Reversa', 'gluteos', 'composto', 'máquina', '3', '12-15', '60s', 'Tronco apoiado, as pernas sobem atrás', false, 'iniciante'),
('Hiperextensão Reversa no Banco', 'gluteos', 'isolado', 'peso corporal', '3', '12-15', '45s', 'Quadril na borda do banco, pernas sobem juntas', false, 'iniciante'),
('Rã Reversa no Banco', 'gluteos', 'isolado', 'peso corporal', '3', '12-15', '45s', 'Calcanhares unidos e joelhos abertos', false, 'iniciante'),
('Pull Through com Elástico', 'gluteos', 'composto', 'elástico', '3', '12-15', '60s', 'Elástico entre as pernas, quadril vai à frente', false, 'iniciante'),
('Afundo Cruzado (Curtsy)', 'gluteos', 'composto', 'halteres', '4', '8-10 cada perna', '90s', 'Perna de trás cruza por trás da da frente', false, 'iniciante'),
('Afundo Lateral com Deslizamento', 'gluteos', 'composto', 'peso corporal', '3', '10-12 cada perna', '60s', 'Um pé desliza pro lado, quadril vai pra trás', false, 'iniciante'),
('Leg Press com Pés Altos', 'gluteos', 'composto', 'máquina', '4', '8-10', '90s', 'Pés no alto da plataforma, empurra com os calcanhares', false, 'iniciante'),
('Agachamento Sumô com Déficit', 'gluteos', 'composto', 'halteres', '4', '8-10', '90s', 'Pés em dois steps, o halter desce entre eles', false, 'intermediario'),
('Levantamento Terra Sumô com Halter', 'gluteos', 'composto', 'halteres', '4', '8-10', '90s', 'Base larga, halter sobe rente ao corpo', false, 'iniciante'),

-- Panturrilha
('Panturrilha em Pé com Halteres', 'panturrilha', 'isolado', 'halteres', '3', '12-15', '45s', 'Halteres ao lado do corpo, sobe o máximo', false, 'iniciante'),
('Panturrilha em Pé com Barra', 'panturrilha', 'isolado', 'barra', '3', '12-15', '45s', 'Barra nas costas, joelhos travados', false, 'intermediario'),
('Panturrilha Sentado com Barra', 'panturrilha', 'isolado', 'barra', '3', '12-15', '45s', 'Barra sobre os joelhos, ponta dos pés numa anilha', false, 'iniciante'),
('Panturrilha Sentado Unilateral com Halter', 'panturrilha', 'isolado', 'halteres', '3', '12-15 cada perna', '45s', 'Halter no joelho, uma perna por vez', false, 'iniciante'),
('Panturrilha Unilateral no Step', 'panturrilha', 'isolado', 'peso corporal', '3', '10-12 cada perna', '45s', 'Uma perna, calcanhar desce abaixo do step', false, 'iniciante'),
('Panturrilha Excêntrica Unilateral', 'panturrilha', 'isolado', 'peso corporal', '3', '10 cada perna', '45s', 'Sobe com as duas pernas, desce com uma em 3s', false, 'iniciante'),
('Panturrilha Unilateral no Leg Press', 'panturrilha', 'isolado', 'máquina', '3', '12-15 cada perna', '45s', 'Uma perna por vez, joelho quase estendido', false, 'iniciante'),
('Panturrilha no Leg Press Horizontal', 'panturrilha', 'isolado', 'máquina', '3', '12-15', '45s', 'Ponta dos pés na borda da plataforma', false, 'iniciante'),
('Panturrilha no Hack', 'panturrilha', 'isolado', 'máquina', '3', '12-15', '45s', 'De frente pro encosto, ponta dos pés na borda', false, 'iniciante'),
('Panturrilha Unilateral em Pé na Máquina', 'panturrilha', 'isolado', 'máquina', '3', '10-12 cada perna', '45s', 'Uma perna por vez, pausa no topo', false, 'iniciante'),
('Panturrilha com Elástico', 'panturrilha', 'isolado', 'elástico', '3', '15-20 cada perna', '30s', 'Sentado, elástico na ponta do pé', false, 'iniciante'),
('Panturrilha Isométrica no Topo', 'panturrilha', 'isolado', 'peso corporal', '3', '30s', '30s', 'Segura na ponta dos pés', false, 'iniciante'),
('Caminhada na Ponta dos Pés', 'panturrilha', 'isolado', 'halteres', '3', '20m', '45s', 'Halteres nas mãos, calcanhares não tocam o chão', false, 'iniciante'),
('Saltitos na Ponta dos Pés (Pogo)', 'panturrilha', 'isolado', 'peso corporal', '3', '20', '45s', 'Joelhos quase travados, contato rápido com o chão', false, 'iniciante'),
('Tibial na Parede', 'panturrilha', 'isolado', 'peso corporal', '3', '15-20', '30s', 'Costas na parede, levanta a ponta dos pés', false, 'iniciante'),
('Tibial com Elástico', 'panturrilha', 'isolado', 'elástico', '3', '15-20 cada perna', '30s', 'Sentado, puxa a ponta do pé contra o elástico', false, 'iniciante'),
('Tibial com Kettlebell', 'panturrilha', 'isolado', 'kettlebell', '3', '12-15 cada perna', '45s', 'Sentado num banco alto, kettlebell no pé', false, 'intermediario'),

-- Abdômen e core (pós-treino)
('Prancha com Joelhos Apoiados', 'core', 'isolado', 'peso corporal', '3', '30s', '30s', 'Joelhos no chão, quadril alinhado', true, 'iniciante'),
('Prancha RKC', 'core', 'isolado', 'peso corporal', '3', '15s', '45s', 'Contrai tudo ao máximo por pouco tempo', true, 'intermediario'),
('Prancha com Alavanca Longa', 'core', 'isolado', 'peso corporal', '3', '20s', '45s', 'Cotovelos à frente da linha dos ombros', true, 'intermediario'),
('Prancha Sobe e Desce', 'core', 'isolado', 'peso corporal', '3', '10-12', '45s', 'Do antebraço pra mão sem balançar o quadril', true, 'intermediario'),
('Prancha Serra (Body Saw)', 'core', 'isolado', 'peso corporal', '3', '10-12', '45s', 'Corpo desliza pra frente e pra trás sobre os antebraços', true, 'intermediario'),
('Prancha com Abertura de Pernas', 'core', 'isolado', 'peso corporal', '3', '30s', '30s', 'Abre e fecha os pés com saltitos', true, 'iniciante'),
('Prancha Aranha', 'core', 'isolado', 'peso corporal', '3', '10 cada lado', '45s', 'Joelho vai ao cotovelo do mesmo lado', true, 'intermediario'),
('Prancha Urso', 'core', 'isolado', 'peso corporal', '3', '30s', '30s', 'Em 4 apoios com os joelhos a 5cm do chão', true, 'iniciante'),
('Caminhada do Urso', 'core', 'isolado', 'peso corporal', '3', '10m', '45s', 'Joelhos baixos, mão e pé opostos avançam juntos', true, 'intermediario'),
('Prancha com Arrasto de Halter', 'core', 'isolado', 'halteres', '3', '8 cada lado', '45s', 'Arrasta o halter de um lado pro outro sem girar', true, 'intermediario'),
('Prancha Reversa', 'core', 'isolado', 'peso corporal', '3', '30s', '30s', 'De barriga pra cima, apoiado nas mãos e calcanhares', true, 'iniciante'),
('Prancha na Bola Suíça', 'core', 'isolado', 'bola', '3', '30s', '45s', 'Antebraços na bola, corpo alinhado', true, 'intermediario'),
('Mexendo a Panela (Stir the Pot)', 'core', 'isolado', 'bola', '3', '8 cada lado', '45s', 'Antebraços na bola desenham círculos', true, 'avancado'),
('Prancha Lateral com Joelho Apoiado', 'core', 'isolado', 'peso corporal', '3', '20s cada lado', '30s', 'Joelho de baixo no chão, quadril alto', true, 'iniciante'),
('Prancha Lateral com Elevação de Quadril', 'core', 'isolado', 'peso corporal', '3', '12 cada lado', '30s', 'Quadril desce quase ao chão e sobe', true, 'iniciante'),
('Prancha Lateral com Elevação de Perna', 'core', 'isolado', 'peso corporal', '3', '10 cada lado', '45s', 'Perna de cima sobe sem o quadril cair', true, 'intermediario'),
('Prancha Lateral com Rotação', 'core', 'isolado', 'peso corporal', '3', '10 cada lado', '45s', 'Braço de cima passa por baixo do tronco', true, 'intermediario'),
('Prancha Copenhagen', 'core', 'isolado', 'peso corporal', '3', '20s cada lado', '45s', 'Perna de cima apoiada no banco, a de baixo no ar', true, 'avancado'),
('Abdominal Completo (Sit-Up)', 'core', 'isolado', 'peso corporal', '3', '15-20', '30s', 'Sobe até sentar, desce vértebra por vértebra', true, 'iniciante'),
('Abdominal Borboleta', 'core', 'isolado', 'peso corporal', '3', '15-20', '30s', 'Solas dos pés unidas, joelhos abertos', true, 'iniciante'),
('Abdominal Remador', 'core', 'isolado', 'peso corporal', '3', '15-20', '30s', 'Abraça os joelhos ao subir, estende ao descer', true, 'iniciante'),
('Abdominal Declinado', 'core', 'isolado', 'peso corporal', '3', '12-15', '45s', 'Pés presos no banco declinado', true, 'intermediario'),
('Abdominal Declinado com Rotação', 'core', 'isolado', 'peso corporal', '3', '10 cada lado', '45s', 'Cotovelo vai ao joelho oposto no topo', true, 'intermediario'),
('Abdominal Cruzado no Solo', 'core', 'isolado', 'peso corporal', '3', '15 cada lado', '30s', 'Ombro vai em direção ao joelho oposto', true, 'iniciante'),
('Abdominal com Pernas a 90°', 'core', 'isolado', 'peso corporal', '3', '15-20', '30s', 'Pernas elevadas, lombar no chão', true, 'iniciante'),
('Abdominal Toque nos Calcanhares', 'core', 'isolado', 'peso corporal', '3', '20 cada lado', '30s', 'Ombros fora do chão, alterna os lados', true, 'iniciante'),
('Abdominal Toque nos Pés', 'core', 'isolado', 'peso corporal', '3', '15-20', '30s', 'Pernas pro teto, mãos buscam os pés', true, 'iniciante'),
('Abdominal Flutter', 'core', 'isolado', 'peso corporal', '3', '30s', '30s', 'Batidas curtas de perna, lombar no chão', true, 'iniciante'),
('Abdominal Sapo', 'core', 'isolado', 'peso corporal', '3', '15-20', '30s', 'Solas unidas no ar, joelhos abertos', true, 'iniciante'),
('Abdominal Lateral Deitado', 'core', 'isolado', 'peso corporal', '3', '15 cada lado', '30s', 'Deitado de lado, cotovelo vai ao quadril', true, 'iniciante'),
('Abdominal em Pé com Joelho ao Cotovelo', 'core', 'isolado', 'peso corporal', '3', '15 cada lado', '30s', 'Mãos na nuca, joelho sobe ao cotovelo oposto', true, 'iniciante'),
('Abdominal McGill', 'core', 'isolado', 'peso corporal', '3', '8 cada lado', '30s', 'Mãos sob a lombar, só a cabeça e os ombros sobem', true, 'iniciante'),
('Abdominal Canivete Alternado', 'core', 'isolado', 'peso corporal', '3', '10 cada lado', '45s', 'Mão toca o pé oposto no alto', true, 'intermediario'),
('Passagem de Bola (V-Pass)', 'core', 'isolado', 'bola', '3', '10-12', '45s', 'Passa a bola das mãos pros pés a cada repetição', true, 'intermediario'),
('Abdominal na Bola Suíça', 'core', 'isolado', 'bola', '3', '15-20', '30s', 'Lombar na bola, amplitude maior', true, 'iniciante'),
('Abdominal na Polia em Pé', 'core', 'isolado', 'polia', '3', '15-20', '30s', 'De costas pra polia alta, enrola o tronco', true, 'iniciante'),
('Encolhimento de Joelhos no Banco', 'core', 'isolado', 'peso corporal', '3', '15-20', '30s', 'Sentado na borda, joelhos vão ao peito', true, 'iniciante'),
('Elevação de Quadril com Pernas Estendidas', 'core', 'isolado', 'peso corporal', '3', '12-15', '30s', 'Pernas pro teto, quadril sai do chão', true, 'iniciante'),
('Elevação de Joelhos Pendurado', 'core', 'isolado', 'peso corporal', '3', '10-12', '45s', 'Joelhos sobem até o quadril, sem balanço', true, 'iniciante'),
('Elevação de Joelhos na Cadeira Romana', 'core', 'isolado', 'máquina', '3', '12-15', '45s', 'Antebraços apoiados, joelhos ao peito', true, 'iniciante'),
('Elevação de Pernas na Cadeira Romana', 'core', 'isolado', 'máquina', '3', '10-12', '45s', 'Pernas estendidas sobem até a horizontal', true, 'intermediario'),
('Pés na Barra (Toes to Bar)', 'core', 'isolado', 'peso corporal', '3', '6-8', '60s', 'Pendurado, os pés tocam a barra', true, 'avancado'),
('Limpador de Para-Brisa Pendurado', 'core', 'isolado', 'peso corporal', '3', '6 cada lado', '60s', 'Pernas no alto giram de um lado ao outro', true, 'avancado'),
('Limpador de Para-Brisa no Solo', 'core', 'isolado', 'peso corporal', '3', '8 cada lado', '45s', 'Pernas a 90° descem pra cada lado', true, 'intermediario'),
('Dragon Flag', 'core', 'isolado', 'peso corporal', '3', '5-6', '90s', 'Só os ombros no banco, corpo reto na descida', true, 'avancado'),
('L-Sit', 'core', 'isolado', 'peso corporal', '3', '10-15s', '60s', 'Pernas estendidas à frente, mãos empurram o apoio', true, 'avancado'),
('Hollow Rock', 'core', 'isolado', 'peso corporal', '3', '15-20', '45s', 'Balança na posição de canoa sem perder a forma', true, 'intermediario'),
('Dead Bug com Bola Suíça', 'core', 'isolado', 'bola', '3', '10 cada lado', '30s', 'Mão e joelho opostos apertam a bola', true, 'iniciante'),
('Flexão Lateral com Halter', 'core', 'isolado', 'halteres', '3', '12-15 cada lado', '30s', 'Um halter só, desce pela lateral da coxa', true, 'iniciante'),
('Flexão Lateral na Polia', 'core', 'isolado', 'polia', '3', '12-15 cada lado', '30s', 'De lado pra polia baixa, tronco inclina pro outro lado', true, 'iniciante'),
('Flexão Lateral no Banco Romano', 'core', 'isolado', 'peso corporal', '3', '10-12 cada lado', '45s', 'De lado no banco romano, sobe sem girar', true, 'intermediario'),
('Rotação de Tronco na Polia', 'core', 'isolado', 'polia', '3', '12 cada lado', '45s', 'Braços estendidos, gira na altura do peito', true, 'iniciante'),
('Rotação de Tronco na Máquina', 'core', 'isolado', 'máquina', '3', '12 cada lado', '45s', 'Quadril fixo, só o tronco gira', true, 'iniciante'),
('Rotação Landmine', 'core', 'isolado', 'barra', '3', '10 cada lado', '45s', 'Ponta da barra vai de um quadril ao outro', true, 'intermediario'),
('Lenhador Invertido na Polia', 'core', 'isolado', 'polia', '3', '12 cada lado', '45s', 'Da polia baixa até acima do ombro oposto', true, 'iniciante'),
('Lenhador com Halter', 'core', 'isolado', 'halteres', '3', '12 cada lado', '45s', 'Do quadril até acima do ombro oposto', true, 'iniciante'),
('Russian Twist sem Peso', 'core', 'isolado', 'peso corporal', '3', '20 cada lado', '30s', 'Pés no chão, mãos tocam o solo de cada lado', true, 'iniciante'),
('Russian Twist com Medicine Ball', 'core', 'isolado', 'medicine ball', '3', '15 cada lado', '45s', 'Bola toca o chão de cada lado', true, 'iniciante'),
('Arremesso de Medicine Ball no Chão', 'core', 'isolado', 'medicine ball', '3', '10-12', '45s', 'Leva acima da cabeça e arremessa com força', true, 'iniciante'),
('Arremesso Lateral de Medicine Ball', 'core', 'isolado', 'medicine ball', '3', '8 cada lado', '45s', 'De lado pra parede, gira o quadril e arremessa', true, 'intermediario'),
('Pallof Press com Elástico', 'core', 'isolado', 'elástico', '3', '12 cada lado', '45s', 'Elástico preso ao lado, estende sem girar', true, 'iniciante'),
('Roda Abdominal em Pé', 'core', 'isolado', 'peso corporal', '3', '5-6', '90s', 'Parte de pé e estende até quase o chão', true, 'avancado'),
('Rollout na Bola Suíça', 'core', 'isolado', 'bola', '3', '10-12', '45s', 'Antebraços rolam a bola à frente', true, 'iniciante'),
('Rollout com Barra', 'core', 'isolado', 'barra', '3', '8-10', '60s', 'Barra com anilhas rola à frente, lombar neutra', true, 'intermediario'),
('Fallout na Fita de Suspensão', 'core', 'isolado', 'fita de suspensão', '3', '8-10', '60s', 'Braços avançam acima da cabeça, corpo reto', true, 'intermediario'),
('Encolhimento de Joelhos na Bola Suíça', 'core', 'isolado', 'bola', '3', '10-12', '45s', 'Pés na bola, traz os joelhos ao peito', true, 'intermediario'),
('Pike na Bola Suíça', 'core', 'isolado', 'bola', '3', '8-10', '60s', 'Pernas estendidas, quadril sobe ao teto', true, 'avancado'),
('Encolhimento de Joelhos na Fita de Suspensão', 'core', 'isolado', 'fita de suspensão', '3', '10-12', '45s', 'Pés nas alças, traz os joelhos ao peito', true, 'intermediario'),
('Pike na Fita de Suspensão', 'core', 'isolado', 'fita de suspensão', '3', '8-10', '60s', 'Pés nas alças, quadril sobe ao teto', true, 'avancado'),
('Encolhimento de Joelhos com Deslizamento', 'core', 'isolado', 'peso corporal', '3', '12-15', '45s', 'Pés deslizam num pano até o peito', true, 'iniciante'),
('Mountain Climber Cruzado', 'core', 'isolado', 'peso corporal', '3', '30s', '30s', 'Joelho vai ao cotovelo oposto', true, 'iniciante'),
('Vácuo Abdominal', 'core', 'isolado', 'peso corporal', '3', '15-20s', '30s', 'Solta o ar e puxa o umbigo pra dentro', true, 'iniciante'),
('Carregada de Mala (Suitcase Carry)', 'core', 'isolado', 'halteres', '3', '20m cada lado', '60s', 'Peso de um lado só, tronco não inclina', true, 'iniciante'),
('Carregada Acima da Cabeça', 'core', 'isolado', 'halteres', '3', '20m cada lado', '60s', 'Braço travado acima da cabeça, costelas fechadas', true, 'intermediario'),
('Levantamento Turco', 'core', 'isolado', 'kettlebell', '3', '3 cada lado', '90s', 'Do chão até ficar de pé com o braço estendido', true, 'avancado'),
('Moinho com Kettlebell', 'core', 'isolado', 'kettlebell', '3', '6 cada lado', '60s', 'Olhos no kettlebell, quadril vai pro lado', true, 'avancado'),

-- Cardio (pós-treino)
('Corrida ao Ar Livre', 'cardio', 'cardio', 'peso corporal', '-', '25min · Moderado', '-', 'Ritmo em que dá pra falar frases curtas', true, 'iniciante'),
('Corrida Leve (Trote)', 'cardio', 'cardio', 'peso corporal', '-', '20min', '-', 'Passadas curtas, respiração tranquila', true, 'iniciante'),
('Corrida Progressiva', 'cardio', 'cardio', 'peso corporal', '-', '25min', '-', 'Começa leve e acelera a cada 5min', true, 'intermediario'),
('Tiros em Subida', 'cardio', 'cardio', 'peso corporal', '-', '8x20s forte', '90s', 'Sobe forte, desce caminhando', true, 'intermediario'),
('Tiros de Corrida', 'cardio', 'cardio', 'peso corporal', '-', '8x100m', '90s', 'Aquece bem antes, esforço de 90%', true, 'intermediario'),
('Corrida Vai e Volta', 'cardio', 'cardio', 'peso corporal', '-', '8x20m', '45s', 'Toca a linha e volta, muda de direção baixo', true, 'intermediario'),
('Deslocamento Lateral', 'cardio', 'cardio', 'peso corporal', '-', '8x20s', '40s', 'Semi-agachado, pés não cruzam', true, 'iniciante'),
('Escada de Agilidade', 'cardio', 'cardio', 'peso corporal', '-', '10min', '-', 'Pés rápidos e leves, olhar à frente', true, 'iniciante'),
('Corrida Estacionária', 'cardio', 'cardio', 'peso corporal', '-', '10min', '-', 'Braços acompanham, pisada leve', true, 'iniciante'),
('Corrida com Joelhos Altos', 'cardio', 'cardio', 'peso corporal', '-', '8x30s', '30s', 'Joelhos sobem até a linha do quadril', true, 'iniciante'),
('Corrida com Calcanhar no Glúteo', 'cardio', 'cardio', 'peso corporal', '-', '8x30s', '30s', 'Calcanhares batem no glúteo, tronco ereto', true, 'iniciante'),
('Esteira — Caminhada Rápida', 'cardio', 'cardio', 'máquina', '-', '30min', '-', '6-6,5km/h sem segurar no apoio', true, 'iniciante'),
('Esteira — Caminhada de Costas', 'cardio', 'cardio', 'máquina', '-', '10min', '-', 'Velocidade baixa, passos curtos', true, 'iniciante'),
('Caminhada com Mochila (Rucking)', 'cardio', 'cardio', 'peso corporal', '-', '30-40min', '-', 'Mochila com carga, postura ereta', true, 'iniciante'),
('Caminhada em Trilha', 'cardio', 'cardio', 'peso corporal', '-', '40-60min', '-', 'Terreno irregular, passos firmes', true, 'iniciante'),
('Subida de Escadaria', 'cardio', 'cardio', 'peso corporal', '-', '15min', '-', 'Sobe em ritmo firme, desce devagar', true, 'iniciante'),
('Step Aeróbico', 'cardio', 'cardio', 'peso corporal', '-', '15min', '-', 'Sobe e desce do step alternando a perna que lidera', true, 'iniciante'),
('Bicicleta ao Ar Livre', 'cardio', 'cardio', 'peso corporal', '-', '40min · Moderado', '-', 'Cadência alta em marcha leve', true, 'iniciante'),
('Bicicleta Reclinada', 'cardio', 'cardio', 'máquina', '-', '25min · Moderado', '-', 'Costas apoiadas, baixo impacto', true, 'iniciante'),
('HIIT na Bicicleta', 'cardio', 'cardio', 'máquina', '-', '10x20s forte', '40s', 'Carga alta nos tiros, bem leve na recuperação', true, 'intermediario'),
('Elíptico Intervalado', 'cardio', 'cardio', 'máquina', '-', '18min', '-', '1min forte / 2min leve', true, 'iniciante'),
('Remo Intervalado', 'cardio', 'cardio', 'máquina', '-', '8x250m', '60s', '250m forte / 1min leve', true, 'intermediario'),
('SkiErg', 'cardio', 'cardio', 'máquina', '-', '15min · Moderado', '-', 'Puxa com os braços e dobra o quadril', true, 'iniciante'),
('Ergômetro de Braço', 'cardio', 'cardio', 'máquina', '-', '15min · Moderado', '-', 'Pedala com os braços, tronco parado', true, 'iniciante'),
('Pular Corda Intervalado', 'cardio', 'cardio', 'peso corporal', '-', '10x1min', '30s', 'Saltos baixos, punhos giram a corda', true, 'iniciante'),
('Pular Corda — Salto Duplo', 'cardio', 'cardio', 'peso corporal', '-', '10x20s', '40s', 'Corda passa duas vezes a cada salto', true, 'avancado'),
('Corda Naval — Batidas Simultâneas', 'cardio', 'cardio', 'peso corporal', '-', '10x20s forte', '40s', 'Os dois braços sobem e batem juntos', true, 'intermediario'),
('Meio Burpee (sem Flexão)', 'cardio', 'cardio', 'peso corporal', '-', '5x1min', '30s', 'Vai à prancha e volta, sem flexão nem salto', true, 'iniciante'),
('Sprawl', 'cardio', 'cardio', 'peso corporal', '-', '6x30s', '30s', 'Joga os pés pra trás e o quadril ao chão', true, 'iniciante'),
('Burpee com Salto no Caixote', 'cardio', 'cardio', 'peso corporal', '-', '5x45s', '45s', 'Emenda o burpee num salto pro caixote', true, 'avancado'),
('Polichinelo sem Salto', 'cardio', 'cardio', 'peso corporal', '-', '10min', '-', 'Um pé abre de cada vez, baixo impacto', true, 'iniciante'),
('Polichinelo Frontal', 'cardio', 'cardio', 'peso corporal', '-', '8x30s', '30s', 'Braços abrem e fecham à frente do peito', true, 'iniciante'),
('Salto Estrela', 'cardio', 'cardio', 'peso corporal', '-', '8x20s', '40s', 'Salta abrindo braços e pernas', true, 'intermediario'),
('Salto Grupado', 'cardio', 'cardio', 'peso corporal', '-', '8x20s', '40s', 'Joelhos sobem ao peito no ar', true, 'intermediario'),
('Patinador', 'cardio', 'cardio', 'peso corporal', '-', '8x30s', '30s', 'Salta de um lado pro outro numa perna só', true, 'iniciante'),
('Boxe no Ar (Shadow Boxing)', 'cardio', 'cardio', 'peso corporal', '-', '6x2min', '45s', 'Golpes soltos, pés sempre em movimento', true, 'iniciante'),
('Wall Ball', 'cardio', 'cardio', 'medicine ball', '-', '5x1min', '45s', 'Agacha e arremessa a bola no alvo', true, 'intermediario'),
('Kettlebell Snatch', 'cardio', 'cardio', 'kettlebell', '-', '8x30s', '30s', 'Do chão até acima da cabeça num movimento só', true, 'avancado'),
('Devil Press', 'cardio', 'cardio', 'halteres', '-', '5x45s', '45s', 'Burpee sobre os halteres e leva acima da cabeça', true, 'avancado'),
('Man Maker', 'cardio', 'cardio', 'halteres', '-', '5x45s', '60s', 'Flexão, remada de cada lado e thruster', true, 'avancado'),
('Circuito com Kettlebell', 'cardio', 'cardio', 'kettlebell', '-', '15min', '-', 'Swing, agachamento e desenvolvimento em sequência', true, 'intermediario'),
('Tabata de Peso Corporal', 'cardio', 'cardio', 'peso corporal', '-', '8x20s forte', '10s', '20s no máximo / 10s de pausa', true, 'intermediario'),
('Aula de Dança', 'cardio', 'cardio', 'peso corporal', '-', '30min', '-', 'Movimento contínuo no ritmo da música', true, 'iniciante'),
('Natação Intervalada', 'cardio', 'cardio', 'piscina', '-', '10x50m', '30s', '50m forte / 30s de pausa', true, 'intermediario'),
('Hidroginástica', 'cardio', 'cardio', 'piscina', '-', '40min', '-', 'Água na altura do peito, sem impacto', true, 'iniciante'),
('Corrida na Piscina', 'cardio', 'cardio', 'piscina', '-', '20min', '-', 'Corre sem tocar o fundo', true, 'iniciante'),

-- Mobilidade e alongamento (pós-treino)
('Alongamento de Peitoral na Parede', 'mobilidade', 'isolado', 'peso corporal', '2', '30s cada lado', '-', 'Antebraço na parede, gira o tronco pro outro lado', true, 'iniciante'),
('Alongamento de Dorsal no Apoio', 'mobilidade', 'isolado', 'peso corporal', '2', '30s', '-', 'Mãos num apoio, quadril vai pra trás', true, 'iniciante'),
('Alongamento de Ombro Cruzado', 'mobilidade', 'isolado', 'peso corporal', '2', '30s cada lado', '-', 'Braço cruza o peito, a outra mão puxa', true, 'iniciante'),
('Alongamento de Tríceps', 'mobilidade', 'isolado', 'peso corporal', '2', '30s cada lado', '-', 'Cotovelo aponta pro teto, mão entre as escápulas', true, 'iniciante'),
('Alongamento de Bíceps na Parede', 'mobilidade', 'isolado', 'peso corporal', '2', '30s cada lado', '-', 'Palma na parede, braço estendido atrás', true, 'iniciante'),
('Alongamento de Flexores do Punho', 'mobilidade', 'isolado', 'peso corporal', '2', '30s cada lado', '-', 'Braço estendido, palma pra cima, puxa os dedos', true, 'iniciante'),
('Alongamento de Extensores do Punho', 'mobilidade', 'isolado', 'peso corporal', '2', '30s cada lado', '-', 'Braço estendido, palma pra baixo, puxa a mão', true, 'iniciante'),
('Alongamento Lateral de Pescoço', 'mobilidade', 'isolado', 'peso corporal', '2', '20s cada lado', '-', 'Orelha vai ao ombro, sem levantar o outro', true, 'iniciante'),
('Alongamento Lateral de Tronco', 'mobilidade', 'isolado', 'peso corporal', '2', '30s cada lado', '-', 'Braço acima da cabeça, inclina pro lado', true, 'iniciante'),
('Alongamento de Posterior Sentado', 'mobilidade', 'isolado', 'peso corporal', '2', '30s', '-', 'Pernas estendidas, tronco vai à frente com a coluna reta', true, 'iniciante'),
('Alongamento de Posterior em Pé', 'mobilidade', 'isolado', 'peso corporal', '2', '30s cada lado', '-', 'Calcanhar à frente, quadril vai pra trás', true, 'iniciante'),
('Alongamento de Quadríceps em Pé', 'mobilidade', 'isolado', 'peso corporal', '2', '30s cada lado', '-', 'Segura o pé atrás, joelhos juntos', true, 'iniciante'),
('Alongamento do Sofá', 'mobilidade', 'isolado', 'peso corporal', '2', '45s cada lado', '-', 'Canela de trás na parede, tronco ereto', true, 'intermediario'),
('Alongamento de Flexor de Quadril Ajoelhado', 'mobilidade', 'isolado', 'peso corporal', '2', '30s cada lado', '-', 'Um joelho no chão, quadril avança', true, 'iniciante'),
('Alongamento de Glúteo (Figura 4)', 'mobilidade', 'isolado', 'peso corporal', '2', '30s cada lado', '-', 'Tornozelo sobre o joelho oposto, puxa a perna', true, 'iniciante'),
('Alongamento do Pombo', 'mobilidade', 'isolado', 'peso corporal', '2', '45s cada lado', '-', 'Perna da frente dobrada, a de trás estendida', true, 'intermediario'),
('Alongamento Borboleta', 'mobilidade', 'isolado', 'peso corporal', '2', '30s', '-', 'Solas dos pés unidas, joelhos descem', true, 'iniciante'),
('Alongamento Sapo', 'mobilidade', 'isolado', 'peso corporal', '2', '45s', '-', 'Joelhos afastados no chão, quadril vai pra trás', true, 'intermediario'),
('Alongamento de Banda Iliotibial', 'mobilidade', 'isolado', 'peso corporal', '2', '30s cada lado', '-', 'Cruza uma perna atrás e inclina pro lado', true, 'iniciante'),
('Alongamento de Panturrilha na Parede', 'mobilidade', 'isolado', 'peso corporal', '2', '30s cada lado', '-', 'Perna de trás estendida, calcanhar no chão', true, 'iniciante'),
('Alongamento de Sóleo na Parede', 'mobilidade', 'isolado', 'peso corporal', '2', '30s cada lado', '-', 'Joelho de trás flexionado, calcanhar no chão', true, 'iniciante'),
('Postura da Criança', 'mobilidade', 'isolado', 'peso corporal', '2', '45s', '-', 'Senta nos calcanhares, braços à frente', true, 'iniciante'),
('Gato-Vaca', 'mobilidade', 'isolado', 'peso corporal', '2', '10', '-', 'Em 4 apoios, arredonda e arqueia a coluna', true, 'iniciante'),
('Postura da Cobra', 'mobilidade', 'isolado', 'peso corporal', '2', '30s', '-', 'Quadril no chão, estende os braços', true, 'iniciante'),
('Cachorro Olhando para Baixo', 'mobilidade', 'isolado', 'peso corporal', '2', '30s', '-', 'Quadril alto, calcanhares buscam o chão', true, 'iniciante'),
('Torção de Coluna Deitado', 'mobilidade', 'isolado', 'peso corporal', '2', '30s cada lado', '-', 'Joelho cruza o corpo, ombros no chão', true, 'iniciante'),
('Joelhos ao Peito Deitado', 'mobilidade', 'isolado', 'peso corporal', '2', '30s', '-', 'Abraça os joelhos, lombar relaxa', true, 'iniciante'),
('Alongamento Escorpião', 'mobilidade', 'isolado', 'peso corporal', '2', '8 cada lado', '-', 'De bruços, o pé busca a mão oposta', true, 'intermediario'),
('Livro Aberto', 'mobilidade', 'isolado', 'peso corporal', '2', '10 cada lado', '-', 'Deitado de lado, braço de cima abre pro outro lado', true, 'iniciante'),
('Rotação Torácica em 4 Apoios', 'mobilidade', 'isolado', 'peso corporal', '2', '10 cada lado', '-', 'Mão na nuca, cotovelo gira pro teto', true, 'iniciante'),
('Maior Alongamento do Mundo', 'mobilidade', 'isolado', 'peso corporal', '2', '5 cada lado', '-', 'Afundo, cotovelo ao chão e braço pro teto', true, 'iniciante'),
('Minhoca (Inchworm)', 'mobilidade', 'isolado', 'peso corporal', '2', '8', '-', 'Caminha com as mãos até a prancha e volta', true, 'iniciante'),
('Agachamento Profundo Sustentado', 'mobilidade', 'isolado', 'peso corporal', '2', '45s', '-', 'Calcanhares no chão, cotovelos abrem os joelhos', true, 'iniciante'),
('Mobilidade de Quadril 90/90', 'mobilidade', 'isolado', 'peso corporal', '2', '8 cada lado', '-', 'Sentado, joelhos tombam de um lado pro outro', true, 'iniciante'),
('Círculos de Quadril', 'mobilidade', 'isolado', 'peso corporal', '2', '8 cada lado', '-', 'Em 4 apoios, o joelho desenha o maior círculo possível', true, 'iniciante'),
('Círculos de Ombro', 'mobilidade', 'isolado', 'peso corporal', '2', '8 cada lado', '-', 'Braço estendido gira devagar, tronco parado', true, 'iniciante'),
('Passagem de Ombro com Bastão', 'mobilidade', 'isolado', 'peso corporal', '2', '10', '-', 'Bastão passa por cima da cabeça com os braços estendidos', true, 'iniciante'),
('Mobilidade de Tornozelo na Parede', 'mobilidade', 'isolado', 'peso corporal', '2', '10 cada lado', '-', 'Joelho toca a parede sem o calcanhar sair do chão', true, 'iniciante'),
('Balanço de Pernas Frontal', 'mobilidade', 'isolado', 'peso corporal', '2', '12 cada perna', '-', 'Apoiado, a perna balança pra frente e pra trás', true, 'iniciante'),
('Balanço de Pernas Lateral', 'mobilidade', 'isolado', 'peso corporal', '2', '12 cada perna', '-', 'Apoiado, a perna balança de um lado pro outro', true, 'iniciante'),
('Extensão Torácica no Rolo', 'mobilidade', 'isolado', 'rolo', '2', '10', '-', 'Rolo no meio das costas, estende pra trás', true, 'iniciante'),
('Liberação Miofascial de Quadríceps', 'mobilidade', 'isolado', 'rolo', '2', '45s cada perna', '-', 'De bruços, rola a frente da coxa devagar', true, 'iniciante'),
('Liberação Miofascial de Posterior', 'mobilidade', 'isolado', 'rolo', '2', '45s cada perna', '-', 'Sentado, rola a parte de trás da coxa', true, 'iniciante'),
('Liberação Miofascial de Glúteo', 'mobilidade', 'isolado', 'rolo', '2', '45s cada lado', '-', 'Sentado no rolo com uma perna cruzada', true, 'iniciante'),
('Liberação Miofascial de Panturrilha', 'mobilidade', 'isolado', 'rolo', '2', '45s cada perna', '-', 'Panturrilha no rolo, uma perna sobre a outra', true, 'iniciante'),
('Liberação Miofascial de Dorsal', 'mobilidade', 'isolado', 'rolo', '2', '45s cada lado', '-', 'Deitado de lado, rolo abaixo da axila', true, 'iniciante')
on conflict (nome) do nothing;
